### ISSUE TITLE
Updates after changed pod template

### ISSUE THREAD

**Issue by fabxc** [coreos/prometheus-operator#49] opened 2016-11-25 13:00 UTC
Currently we just inspect the version suffix of the base image to determine whether all containers are in sync. We can change the entire pod template though and it the new resource field in the Prometheus TPR we actually do.

So we'd need something like `pod_template_hash` labels like Deployments use eventually.
It's all still up in the air how the PetSet controller will provide updates later on. If it will also use that label, we will be conflicting again.

Possibly we'd just do a an on the fly hash for now or simply track all mutable template fields until it's figured out what the PetSet controller will do.

**Comment by whereisaaron** [comment] 2017-02-24 05:51
I updated a Prometheus resource to add an `externalUrl` config. The statefulset was updated to add the command `-web.external-url` line argument, but the (single) pod was not recreated with the new argument. I had to manually delete the pod, which was them recreated with the new command line argument.

Is this problem caused by the issue you raise @fabxc? 

I also notice that the `creationTimestamp` for the statefulsets and pvcs created by prometheus-operator are always `null`, that seems incorrect?

**Comment by brancz** [comment] 2017-04-06 08:13
StatefulSets are targeted to get rolling updates in 1.7, so we will just wait for that to land.

**Comment by brancz** [comment] 2017-07-24 12:54
So rolling deployments have indeed landed in 1.7 and StatefulSets can be fully mutated without any errors. However, to automatically rollout these changes the Pods still have to be deleted manually, or we have to implement using the actual rolling deployments the StatefulSet now offers.

**Closed** 2017-08-07 12:07 UTC
