### ISSUE TITLE
Opening storage failed, permission denied

### ISSUE THREAD

**Issue by nuala33** [coreos/prometheus-operator#830] opened 2017-12-15 22:58 UTC
Similar to #541, I am having the same issue where when I include my usual volumeClaimTemplate block to my Prometheus configuration, my pods get stuck in a crash loop with the error:
```
level=info ts=2017-12-15T22:51:22.073242152Z caller=main.go:314 msg="Starting TSDB"
level=error ts=2017-12-15T22:51:22.074477852Z caller=main.go:323 msg="Opening storage failed" err="open DB in /var/prometheus/data: open /var/prometheus/data/181997666: permission denied"
```
This only started happening once I upgraded from Prometheus 1.8 to 2.0.

Things I have tried:
Deleting my persistent volumes and re-adding them, and adding the following to my prometheus-k8s.yaml file:
```
spec:
  securityContext:
    runAsUser: 1000
    fsGroup: 2000
    runAsNonRoot: true
```

I am running the newest version of prometheus-operator (0.15.0).
I also can't exec -ti to ssh to the pod so I can't look at or change permissions on /var/prometheus/data. Any ideas?

**Comment by loganasherjones** [comment] 2017-12-19 14:04
As far as I know, setting the `securityContext` in the `Prometheus` definition shouldn't change anything. Perhaps this is something that should be allowed? I'd have to defer to the team.

In any case, I'm having this issue as well, but as far as I can tell, it's due to the fact that the provisioner I'm using ([cephfs-provisioner](https://github.com/kubernetes-incubator/external-storage/tree/master/ceph/cephfs) isn't respecting the `securityContext`. I've [created an issue](https://github.com/kubernetes-incubator/external-storage/issues/515) in that to track. We'll see what they say. 

I know this doesn't necessarily help you, but I believe this problem is _usually_ caused by whatever is provisioning your volume.

**Comment by brancz** [comment] 2017-12-21 11:25
> This only started happening once I upgraded from Prometheus 1.8 to 2.0.

This is probably the crooks of the issue. The Prometheus docker image changed from `root` user to `nobody`. I can imagine that to be a problem if you use the same volume in 1.x and the upgrade to 2.0 and all the permissions are already set. You may be able to just chown everything to your user, that's what I would try. If not I recommend starting with a new clean volume.

**Comment by nuala33** [comment] 2018-01-11 22:50
Hey @brancz! I wasn't sure who the correct user should be, because my user had been "nfsnobody" all along on my NFS server (it wasn't root originally). But what I did do is make sure all the Prometheus storage files on my NFS host were chmod 777'd, and from there my pods were able to start up running the new version (Prometheus 2.0). However, when I looked at all my old files that were still there from Prometheus 1.8, I noticed none of them were being updated by new my prometheus instances. I'm talking about the ones that look like this, for example:

```
drwx------ 2 nfsnobody nfsnobody    643072 Jan 11 18:27 00
drwx------ 2 nfsnobody nfsnobody    638976 Jan 11 18:29 01
drwx------ 2 nfsnobody nfsnobody    606208 Jan 11 18:31 02
```

So I went ahead and deleted everything in the prometheus-db directory that my Prometheus 1.8 instances had created on my NFS host, except for the write ahead log (wal) directory, which I wasn't allowed to delete. And now the wal dir is the only thing I am seeing my prometheus pods writing to under their /var/prometheus/data directory. I have tested the persistence by running `kubectl delete prometheus ny5` and re-creating my pods. I still see my data from before, presumably because of that write ahead log. So to me it looks like everything is working how it should now, but it looks so different from the previous structure that I just want to double check that it's correct. Is this really all I should be seeing under /var/prometheus/data?

```
/prometheus $ ls -l /var/prometheus/data/
total 4
-rw-------    1 1000     nogroup          2 Jan 11 22:32 lock
drwxr-xr-x    2 1000     nogroup         32 Jan 11 22:32 wal
```

**Comment by brancz** [comment] 2018-01-12 08:57
Thanks for the elaborate comment @nuala33! All of that looks correct, except that the lock shouldn't be there, but we're fixing that with #855, and are about to do a release with that fix. Note that NFS is a bit wonky though, we've seen a couple of odd things being reported to Prometheus when using NFS as it's not POSIX compliant and we require that in Prometheus (see https://github.com/prometheus/prometheus/issues/3506, https://github.com/prometheus/prometheus/issues/3534), if possible I recommend using a different solution.

**Comment by whereisaaron** [comment] 2018-02-09 20:04
@brancz NFSv4 is POSIX compliant I believe? I think you are thinking of the old NFSv3? Certainly [AWS EFS is claiming POSIX compliance](https://docs.aws.amazon.com/efs/latest/ug/creating-using.html) for its NFSv4 clusters.

In the prometheus/prometheus#3534 example they [solved the NFS problem](https://github.com/prometheus/prometheus/issues/3534#issuecomment-350324174) by updating to a newer `tsdb` build rather than switching from NFS: *"For what it's worth, we built Prometheus against the latest prometheus/tsdb and that solved this particular issue with NFS"*

And in the prometheus/prometheus#3506 example they also cite a [`tsdb` bug fix](https://github.com/prometheus/tsdb/pull/213/files) as the solution.

**Comment by aagarwalincontact** [comment] 2018-02-27 23:59
I am trying with to run below commands and looking for docker logs , still getting the 
"Opening storage failed open DB in /prometheus/data/: open /prometheus/data/245726561: permission denied"
**Any insights will really help**

##################
mkdir -p /prometheus/data/
chown ec2-user:ec2-user /prometheus/data/

# To configure your EC2 instance to mount an EFS file system automatically at launch
echo "${file_system_id}.efs.${region}.amazonaws.com:/ /prometheus/data/ nfs4 nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 0 0" >> /etc/fstab
mount -a -t nfs4

#Use the efs mount as target to persist prometheus metrics
sudo docker run -d -p 9090:9090 -v /prometheus/data:/prometheus/data prom/prometheus:master --config.file=/prometheus/configfile/prometheus.yml --storage.tsdb.path=/prometheus/data/

**Comment by whereisaaron** [comment] 2018-02-28 02:35
Hi @aagarwalincontact prometheus-operator is for Kubernetes, so you use Kubernetes to mount the EFS volume into the container. Either using the Deployment/StatefulSet `volumes` / `volumeMounts` or using a PVC with [`efs-provisioner`](https://github.com/wongma7/efs-provisioner).

```
volumes:
  - name: efs-volume
    nfs:
      path: /prometheus/data/
      server: fs-12345678.efs.us-east-2.amazonaws.com
```

Also, it is unlikely the container is running as `ec2-user`. So that uid will unexpected inside the container and possibly the cause of your error.

**Comment by bamb00** [comment] 2018-03-24 17:01
@brancz I'm running into the same issue.  Had to set the volume path to 775 for the subpath prometheus-db to mount.  Does not work with chmod 755.

       level=info ts=2018-03-24T16:25:47.133107849Z caller=targetmanager.go:68 component="target manager" msg="Starting target manager..."
       level=error ts=2018-03-24T16:25:47.133300991Z caller=main.go:324 msg="Opening storage failed" err="open DB in /var/prometheus/data: open /var/prometheus/data/223095208: permission denied"

Prometheus configuration,

       spec:
         securityContext:
            runAsUser: 1000
            fsGroup: 2000
            runAsNonRoot: true


       /var/prometheus/data $ ls -l
       total 4
      -rw-------     1 1000     root             2 Mar 24 16:42 lock
      drwxr-xr-x    2 1000     root            20 Mar 24 16:42 wal

Also, When the securityContext is set "priviledged: true"? the prometheus configuration set it to,

         securityContext:
            runAsUser: 1000
            fsGroup: 2000
            runAsNonRoot: true

Thanks.

**Comment by brancz** [comment] 2018-03-26 08:59
@bamb00 which version of the Prometheus Operator are you using? And what does the generated Pod object look like in the end?

**Comment by bamb00** [comment] 2018-03-26 14:29
@brancz Using prometheus-operator 0.14 and prometheus image v2.0.0-rc1.  How can I override the user id 1000 to root?

**Comment by brancz** [comment] 2018-03-26 18:04
The ability to specify a custom security context has only been supported since 0.17 : https://github.com/coreos/prometheus-operator/releases/tag/v0.17.0

**Comment by bamb00** [comment] 2018-04-05 23:12
@brancz Thanks for the info.  Change to prometheus-operator v0.17 and was able to adjust the permission  to /var/prometheus/data.

**Comment by brancz** [comment] 2018-04-06 06:42
I’m going to close this as the Prometheus operator exposes all options for you to configure permissions, user and group.

If the volume provider you are using does not support the kubelet setting appropriate permissions, then it’s up to you to ensure this.

**Closed by brancz** 2018-04-06 06:42 UTC

**Comment by alokhom** [comment] 2019-05-24 10:52
make a config folder in the location of your docker-compose.yml. insert the files prometheus.yml and alert_rules.yml in the config folder. This code worked for me on v2.10 prometheus image
```
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - './config:/prometheus'
    restart: unless-stopped
    ports:
      - 9090:9090
```

**Comment by alokhom** [comment] 2019-05-24 10:52
make a config folder in the location of your docker-compose.yml. insert the files prometheus.yml and alert_rules.yml in the config folder. This code worked for me on v2.10 prometheus image
```
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - './config:/prometheus'
    restart: unless-stopped
    ports:
      - 9090:9090
```

**Comment by yashrahurikar23** [comment] 2021-06-10 23:16
If you have a dedicated Prometheus user give that user permission to access the /var/lib/prometheus folder
You can refer this article if this helps: https://linuxhint.com/install_prometheus_ubuntu/
