### ISSUE TITLE
Support the ability to use the remote_write feature in prometheus to export metrics to graphite or influxDB

### ISSUE THREAD

**Issue by mmerrill3** [coreos/prometheus-operator#386] opened 2017-05-24 15:02 UTC
Expected the ability to use the remote_write feature in prometheus to write metrics to a remote time series database like graphite or InfluxDB.

We will most likely be implementing this, so this is a placeholder for a future pull request.

**Comment by brancz** [comment] 2017-05-24 15:31
`remote_write` is a highly experimental feature in upstream Prometheus, it is too unstable and changes too quickly for an integration to make sense at this point. Once stabilized it makes sense, but until then I think a custom configuration is the way to go here.

**Comment by mmerrill3** [comment] 2017-05-31 19:40
Thanks @brancz, we'll look at the custom configuration

**Comment by brancz** [comment] 2017-06-12 12:19
This is actually a duplicate of #352. Closing here, we'll continue the discussion and updates in the other thread.

**Closed by brancz** 2017-06-12 12:19 UTC
