### ISSUE TITLE
[helm/grafana] admin secrets

### ISSUE THREAD

**Issue by ozbillwang** [coreos/prometheus-operator#1618] opened 2018-07-14 11:20 UTC
**What did you do?**

deploy kube-prometheus, it will deploy its own grafana chart as well. 

**What did you expect to see?**

I'd like the admin password auto-generated, not hard code to `admin`

Or get secrets from kubernetes secrets

**What did you see instead? Under which circumstances?**

hard code password `admin` every time, when deploy a new prometheus stack.

**Environment**

helm v2.9.1 kubectl v1.10.5

* Kubernetes version information:

helm v2.9.1 kubectl v1.10.5

* Kubernetes cluster kind: 

      AWS EKS

### another question about grafana. 

Why manage own Grafana chart in this repo,  point to `stable/grafana` should be easier, more supports on it and you needn't care the bugs in it.

**Comment by gianrubio** [comment] 2018-07-17 14:42
thanks for your feedback @ozbillwang. 
I'm closing this issue because it's duplicate of https://github.com/coreos/prometheus-operator/issues/592#issuecomment-346468179

**Closed by gianrubio** 2018-07-17 14:42 UTC
Labels: helm
