### ISSUE TITLE
Grafana: Unable to Log in, mkdir permission denied

### ISSUE THREAD

**Issue by christianTragesser** [coreos/prometheus-operator#924] opened 2018-01-25 15:56 UTC
**What did you do?**
Pulled latest changes(1.25.2018) and ran kube-prometheus deploy.  Added ingress for grafana service, went to grafana landing page, navigate to Sign in, input credentials and submit.

**What did you expect to see?**
Expected to be logged into grafana user UI

**What did you see instead? Under which circumstances?**
Error message:
Server side error :(
runtime error: index out of range
Check Grafana server logs for detailed error message.

Inspecting the log shows:
 lvl=eror msg="Failed to start session" logger=context error="mkdir /grafana/data: permission denied"

**Environment**
attempted on two separate clusters

* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:16:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
KOPS

* Manifests:
unedited repo manifests

**Comment by christianTragesser** [comment] 2018-01-25 18:56
Not seeing this issue with commit 564f78eabf9bc4ecb53913c9412107bbe06b95b3, FWIW

**Comment by sebglon** [comment] 2018-01-26 10:48
Have you deployed with Helm?

**Comment by christianTragesser** [comment] 2018-01-26 13:41
Not deploying with Helm.  Our process implements the kube-prometheus/hack/cluster-monitoring/deploy script.

**Comment by brancz** [comment] 2018-01-26 13:44
That's curious. We did just change the Grafana image to build our own: https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/grafana/grafana-deployment.yaml#L17

The source for the image is here: https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus/grafana-image

**Comment by christianTragesser** [comment] 2018-01-26 14:40
No changes have been applied to the implementation of grafana.  We have applied an ingress rule allowing us to access the Grafana externally, but that is it.

**Comment by burdara** [comment] 2018-01-26 20:21
I ran into this exact issue using the `./hack/cluster-monitoring/self-hosted-deploy`.  I was able to resolve it by updating the `grafana-deployment.yaml` manifest to include the following environment variable:

```
containers:
- name: grafana
  ...
  env:
  - name: GF_PATHS_DATA
    value: /data
  ...
```

Ideally,  the `config.toml` should set this value as part of the build.  If I get some time, I will put together a PR, unless someone beats me to it.

**Comment by brancz** [comment] 2018-01-29 14:21
That's curious. This is actually already configured here: https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/grafana-image/config.toml#L2

**Comment by burdara** [comment] 2018-01-29 14:51
@brancz that is the `database.path` setting.  The configuration I referenced is `paths.data`.  There is some overlap between these;  however, they are not the same.

Per [grafana documentation](http://docs.grafana.org/installation/configuration/):

`paths.data`
>Path to where Grafana stores the sqlite3 database (if used), **file based sessions (if used), and other data**. This path is usually specified via command line in the init.d script or the systemd service file.

`database.path`
>Only applicable for sqlite3 database. The file path where the database will be stored.

The important difference is **"file based sessions (if used), and other data"**.

**Comment by brancz** [comment] 2018-01-29 15:23
I see! Then your suggestion makes sense. Let's add it to the manifest.

**Comment by gitfrederic** [comment] 2018-02-03 22:20
I also encountered this issue.  The cause is:

https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/grafana-image/Dockerfile#L13 , i.e.:

```
WORKDIR    /grafana
```

This directory is write-able only by `root`, i.e.:

```
$ ls -l1 / | grep grafana
drwxr-xr-x   1 root root 4096 Jan 23 14:17 grafana
```

but the `non-root` version of Grafana isn't running as `root` (it looks like it's running as `nobody`).

As mentioned in another comment, the [paths] defaults at https://github.com/grafana/grafana/blob/v4.6.3/conf/defaults.ini#L13 need to be overridden to use `/data` instead of `data`.

Changing https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/grafana-image/config.toml to contain the following resolves the issue:

```
[database]
path = /data/grafana.db

[paths]
data = /data
logs = /data/log
plugins = /data/plugins
```

**Comment by brancz** [comment] 2018-04-12 08:17
Closing as #924 was merged

**Closed by brancz** 2018-04-12 08:17 UTC
