### ISSUE TITLE
etcd3 metrics missing 

### ISSUE THREAD

**Issue by fragtom** [coreos/prometheus-operator#571] opened 2017-08-17 15:44 UTC
I installed all the prometheus-operator examples, quite a lot of metrics.. 

But missing etcd metrics..  Have running

```tom.stark@MBproTStark prometheus-monitoring (aws)  $ kubectl -n monitoring get ep
NAME                    ENDPOINTS                                                              AGE
alertmanager-main       10.244.18.7:9093,10.244.46.10:9093,10.244.83.18:9093                   14d
alertmanager-operated   10.244.18.7:9093,10.244.46.10:9093,10.244.83.18:9093 + 3 more...       14d
etcd-k8s                10.142.0.2:2379                                                        1h
grafana                 10.244.46.7:3000                                                       14d
kube-state-metrics      10.244.46.6:8080                                                       14d
node-exporter           172.31.1.143:9100,172.31.10.210:9100,172.31.18.136:9100 + 12 more...   14d
postgres-exporter       172.31.27.181:9187                                                     8d
prometheus-k8s          10.244.18.9:9090,10.244.8.10:9090                                      14d
prometheus-operated     10.244.18.9:9090,10.244.46.12:9090,10.244.8.10:9090                    14d
prometheus-operator     10.244.46.4:8080                                                       14d
redis-exporter          172.31.27.181:9121           
```

and getting on http://localhost:2379/metrics (```kubectl proxy --port 2379```) not the expected results of  *etcd_server* values.. 

Kubernetes version information: 
```
tom.stark@MBproTStark prometheus-monitoring (aws)  $ kubectl --context=aws version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T19:06:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6+coreos.1", GitCommit:"42a5c8b99c994a51d9ceaed5d0254f177e97d419", GitTreeState:"clean", BuildDate:"2017-06-21T01:10:07Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by brancz** [comment] 2017-08-21 09:43
The problem is that etcd is typically quite locked down and is very different in its deployment. Essentially what you need is a `Endpoints` objects in your Kubernetes cluster, that includes the IP port combination that fits your cluster. An example for manual provisioning an `Endpoints` object can be found here: 

https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/etcd/etcd-bootkube-vagrant-multi.yaml

**Comment by fragtom** [comment] 2017-08-22 09:37
I added  that svc and ep, replaced IP addresses for my setup .. but there is no metric ```etcd_server```


```
tom.stark@MBproTStark prometheus-monitoring (aws)  $ kubectl -n monitoring get svc,ep | grep etcd
svc/etcd-k8s                10.100.216.208   <none>        2379/TCP            3m
ep/etcd-k8s                10.142.0.2:2379                                                        3m
```

Is it right, that ep and svc could resist in ```monitoring``` namespace?

**Comment by brancz** [comment] 2017-08-22 10:32
Since this is just a manually maintained list of IPs, it doesn't actually matter where these objects are. You do need to make sure there is a `ServiceMonitor` object, that selects that `Service`/`Endpoints` object. Like this one: https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-service-monitor-kube-controller-manager.yaml

**Comment by fragtom** [comment] 2017-08-22 13:54
Thank you for response and hinting that. But I'm so sorry for my bad explanation on that, what I in general mean is, that I'm searching for the ```etcd_server``` items in the metrics.. I expect, that they should be listet on the etcd-k8s svc.. The snippet from the /metrics .. only etcd_helper_* and etcd_request_* entries listed.. concerning the documentation of https://coreos.com/blog/developing-prometheus-alerts-for-etcd.html  the etcd_server metrics should be listed.. 

````
apiserver_request_latencies_summary{resource="statefulsets",verb="LIST",quantile="0.9"} NaN
apiserver_request_latencies_summary{resource="statefulsets",verb="LIST",quantile="0.99"} NaN
apiserver_request_latencies_summary_sum{resource="statefulsets",verb="LIST"} 443
apiserver_request_latencies_summary_count{resource="statefulsets",verb="LIST"} 1
apiserver_request_latencies_summary{resource="statefulsets",verb="WATCH",quantile="0.5"} 4.13000323e+08
apiserver_request_latencies_summary{resource="statefulsets",verb="WATCH",quantile="0.9"} 5.32000506e+08
apiserver_request_latencies_summary{resource="statefulsets",verb="WATCH",quantile="0.99"} 5.32000506e+08
apiserver_request_latencies_summary_sum{resource="statefulsets",verb="WATCH"} 1.05957986482e+11
apiserver_request_latencies_summary_count{resource="statefulsets",verb="WATCH"} 254
apiserver_request_latencies_summary{resource="storageclasses",verb="LIST",quantile="0.5"} NaN
apiserver_request_latencies_summary{resource="storageclasses",verb="LIST",quantile="0.9"} NaN
apiserver_request_latencies_summary{resource="storageclasses",verb="LIST",quantile="0.99"} NaN
apiserver_request_latencies_summary_sum{resource="storageclasses",verb="LIST"} 444
apiserver_request_latencies_summary_count{resource="storageclasses",verb="LIST"} 2
apiserver_request_latencies_summary{resource="storageclasses",verb="WATCH",quantile="0.5"} 3.90000333e+08
apiserver_request_latencies_summary{resource="storageclasses",verb="WATCH",quantile="0.9"} 5.44000343e+08
apiserver_request_latencies_summary{resource="storageclasses",verb="WATCH",quantile="0.99"} 5.44000343e+08
apiserver_request_latencies_summary_sum{resource="storageclasses",verb="WATCH"} 1.05768279043e+11
apiserver_request_latencies_summary_count{resource="storageclasses",verb="WATCH"} 253
apiserver_request_latencies_summary{resource="thirdpartyresources",verb="LIST",quantile="0.5"} NaN
apiserver_request_latencies_summary{resource="thirdpartyresources",verb="LIST",quantile="0.9"} NaN
apiserver_request_latencies_summary{resource="thirdpartyresources",verb="LIST",quantile="0.99"} NaN
apiserver_request_latencies_summary_sum{resource="thirdpartyresources",verb="LIST"} 442692
apiserver_request_latencies_summary_count{resource="thirdpartyresources",verb="LIST"} 139
apiserver_request_latencies_summary{resource="thirdpartyresources",verb="WATCH",quantile="0.5"} 1918
apiserver_request_latencies_summary{resource="thirdpartyresources",verb="WATCH",quantile="0.9"} 3652
apiserver_request_latencies_summary{resource="thirdpartyresources",verb="WATCH",quantile="0.99"} 14225
apiserver_request_latencies_summary_sum{resource="thirdpartyresources",verb="WATCH"} 1.659086944e+09
apiserver_request_latencies_summary_count{resource="thirdpartyresources",verb="WATCH"} 10141
# HELP authenticated_user_requests Counter of authenticated requests broken out by username.
# TYPE authenticated_user_requests counter
authenticated_user_requests{username="admin"} 4048
authenticated_user_requests{username="other"} 509369
# HELP etcd_helper_cache_entry_count Counter of etcd helper cache entries. This can be different from etcd_helper_cache_miss_count because two concurrent threads can miss the cache and generate the same entry twice.
# TYPE etcd_helper_cache_entry_count counter
etcd_helper_cache_entry_count 0
# HELP etcd_helper_cache_hit_count Counter of etcd helper cache hits.
# TYPE etcd_helper_cache_hit_count counter
etcd_helper_cache_hit_count 0
# HELP etcd_helper_cache_miss_count Counter of etcd helper cache miss.
# TYPE etcd_helper_cache_miss_count counter
etcd_helper_cache_miss_count 0
# HELP etcd_request_cache_add_latencies_summary Latency in microseconds of adding an object to etcd cache
# TYPE etcd_request_cache_add_latencies_summary summary
etcd_request_cache_add_latencies_summary{quantile="0.5"} NaN
etcd_request_cache_add_latencies_summary{quantile="0.9"} NaN
etcd_request_cache_add_latencies_summary{quantile="0.99"} NaN
etcd_request_cache_add_latencies_summary_sum 0
etcd_request_cache_add_latencies_summary_count 0
# HELP etcd_request_cache_get_latencies_summary Latency in microseconds of getting an object from etcd cache
# TYPE etcd_request_cache_get_latencies_summary summary
etcd_request_cache_get_latencies_summary{quantile="0.5"} NaN
etcd_request_cache_get_latencies_summary{quantile="0.9"} NaN
etcd_request_cache_get_latencies_summary{quantile="0.99"} NaN
etcd_request_cache_get_latencies_summary_sum 0
etcd_request_cache_get_latencies_summary_count 0
# HELP get_token_count Counter of total Token() requests to the alternate token source
# TYPE get_token_count counter
get_token_count 0
# HELP get_token_fail_count Counter of failed Token() requests to the alternate token source
# TYPE get_token_fail_count counter
get_token_fail_count 0
# HELP go_gc_duration_seconds A summary of the GC invocation durations.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 0.00040487600000000003
```

**Comment by brancz** [comment] 2017-08-22 13:59
Those metrics look like they're from the apiserver. Are you sure you picked up the right IP address? What does your setup look like? As in which tools did you use to privision your cluster, kubernetes version, etc?

**Comment by fragtom** [comment] 2017-08-22 14:33
I installed exactly that https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/README.md setup, but without helm.. In my initial description I display the service and endpoints.

But I'm not sure to get the right IP for putting into the setup .. What ip address I have to use?

https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/etcd/etcd-bootkube-vagrant-multi.yaml

**Comment by VinceMD** [comment] 2017-08-29 06:45
I've got the same issues. Probably from lack of understanding

1. Created an etcd service and endpoints in monitoring space:
```kind: Service
apiVersion: v1
metadata:
  name: etcd-k8s
spec:
  ports:
  - protocol: TCP
    port: 2379
    targetPort: 2379
---
kind: Endpoints
apiVersion: v1
metadata:
  name: etcd-k8s
subsets:
  - addresses:
      - ip: 10.11.12.52
    ports:
      - port: 2379```

where 10.11.12.52 is the IP of my etcd node. It's an EC2 instance (I use kube-aws 0.9.7 and for this cluster I have only 1 etcd node)

2. I've opened port 2379 on 10.11.12.52 to the world for time being

3. I've created the service monitor https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-service-monitor-kube-controller-manager.yaml 
Although from reading this file I don't understand what it is doing.

4. check Prometheus console in the web UI. I see etcd_helper_* and etcd_request_*. Whereas I expected metrics like `etcd_server_has_leader`

What step am I missing? would you be able to clarify the flow, as in how the components interact with each other

**Comment by brancz** [comment] 2017-08-29 07:23
The `etcd_helper_*` metrics are actually coming from the apiserver, not etcd. You are not successfully discovering etcd yet.

The `ServiceMonitor` you referenced needs to be adapted, as it specifically selects only those service/endpoints objects that have the `k8s-app: kube-controller-manager` label. What you need to do is label your service and endpoints object properly and then adapt the `ServiceMonitor` manifest. You should end up with something like this (assuming you are deploying this in the monitoring namespace).

```
apiVersion: v1
kind: Service
metadata:
  name: etcd-k8s
  labels:
    k8s-app: etcd-k8s
spec:
  ports:
  - protocol: TCP
    port: 2379
    targetPort: 2379
---
apiVersion: v1
kind: Endpoints
metadata:
  name: etcd-k8s
  labels:
    k8s-app: etcd-k8s
subsets:
  - addresses:
    - ip: 10.11.12.52
    ports:
    - port: 2379
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: etcd-k8s
  labels:
    k8s-app: etcd-k8s
spec:
  jobLabel: k8s-app
  endpoints:
  - targetPort: 2379
    interval: 30s
  selector:
    matchLabels:
      k8s-app: etcd-k8s
  namespaceSelector:
    matchNames:
    - monitoring
```

I haven't tried this out, but it should give you guidance. Let me know how it goes :slightly_smiling_face: .

**Comment by VinceMD** [comment] 2017-08-29 10:00
This works, thanks! Now just need to configure the ServiceMonitor it to use SSL as etcd will only respond over SSL. 
I will test that over my kube-aws cluster and provide feedback so others can use this configuration in the future

**Comment by VinceMD** [comment] 2017-08-30 05:37
I'm able to curl my etcd endpoint by passing the certificates:

`curl -L -v  --cacert ./ca.pem --cert ./etcd-client.pem --key ./etcd-client-key.pem https://etcd0.mycompany-internal-domain.local:2379/metrics`

Where etcd0.mycompany-internal-domain.local is the full DNS for my first etcd node. I have 3 of them, each with its own DNS (Route53) 
* etcd0.mycompany-internal-domain.local
* etcd0.mycompany-internal-domain.local
* etcd1.mycompany-internal-domain.local

I want to alter the ServiceMonitor spec to specify tlsConfig:
```
spec:
  jobLabel: k8s-app
  endpoints:
  - port: api
    interval: 30s
    scheme: https
    tlsConfig:
      caFile: credentials/ca.pem
      certFile: credentials/etcd-client.pem
      keyFile: credentials/etcd-client-key.pem
```
where `credentials` is the path to the credential folder on my laptop.

The problem I see is that Endpoint takes an IP address:
``` subsets:
- addresses:
  - ip: 10.11.12.52
    nodeName: 10.11.12.52
```
The certificates are not valid for the IP address. Not a valid name. I tried with curl, it won't take it.
How can I use DNS based service? 

Kubernetes has the concept of ExternalName for a service:
```
spec:
  type: ExternalName
  externalName: etcd0.mycompany-internal-domain.local
```
How do I link the ServiceMonitor to this ExternalName endpoint?

**Comment by VinceMD** [comment] 2017-08-31 11:31
So I thought I could use the IP of my etcd nodes for time being with the `insecureSkipVerify` option for time being, until I generate certificates that work for both the IP and DNS address.

With the Certificates options:
```
      caFile:
      certFile: 
      keyFile:
```

Where are those files expected? Is that a location inside the Prometheus container? Or on the host VM? 
I assume the etcd certificates are not available to the kubernetes nodes/workers but only by controllers? What is the best practice here?

**Comment by VinceMD** [comment] 2017-08-31 12:00
I think I'm getting close: https://github.com/coreos/prometheus-operator/pull/264
Secrets available in the namespace can be mounted into the pod

The alternative, as explained on the ticket, would be to bake a Prometheus image which includes the certificates.

it's the first time I see Kubernetes secrets used to store a file i

**Comment by VinceMD** [comment] 2017-08-31 12:36
I got it working :). Problem solved for me

**Comment by VinceMD** [comment] 2017-09-01 00:13
Created a doc in the repo and wanted to push a pull request but I'm not authorised.

Here is the doc in a Gist: https://gist.github.com/VinceMD/43c7afc1a6b0f580b0cb6fb27e650042

**Comment by jeremyd** [comment] 2017-09-01 18:12
https://gist.github.com/jeremyd/1fffeaf3e9acc0165bbcd9c33286287c  @VinceMD here's what I use for grafana dash, it's a mix of host metrics and etcd metrics.  Maybe you can make it better and add it to grafana.net :)

**Comment by VinceMD** [comment] 2017-09-01 23:34
Thanks I made one quickly  yesterday and published on Grafana: https://grafana.com/dashboards/3070

I didn't include host metrics. Are they available with the etcd_ label? 

I will check your gist on Monday and see if I can merge and republish on Grafana

**Comment by brancz** [comment] 2017-09-04 09:38
Sorry I was on vacation, and am only slowly working myself through issues and PRs.

@VinceMD we'd be happy if you could create a PR to add this to the docs. Anyone should be able to open a PR, just fork the repository, commit your doc and open the PR. Once we merge your doc, I would say we can close this issue :slightly_smiling_face: 

Regarding an etcd grafana dashboard, the etcd team maintains a grafana dashboard and ensures it's up to date and high quality: https://github.com/coreos/etcd/blob/master/Documentation/op-guide/monitoring.md#grafana

**Comment by VinceMD** [comment] 2017-09-06 02:03
@brancz Documentation pull request here https://github.com/coreos/prometheus-operator/pull/601

Improvements welcome.

PS: I include in the doc an etcd dashboard that I've uploaded to Grafana.com. It's based on the official etcd one but working with Prometheus and I've added some metrics that were mentioned on the CoreOs metrics doc and were not present in the dashboard

**Comment by brancz** [comment] 2017-09-13 11:29
Closing here as @VinceMD added some nice docs around this in #601 . Thanks!

**Closed by brancz** 2017-09-13 11:29 UTC
