### ISSUE TITLE
Add StatefulSetMetadata to PrometheusSpec

### ISSUE THREAD

**Issue by Devin-Holland** [coreos/prometheus-operator#2642] opened 2019-06-14 15:11 UTC
**What is missing?**
Missing the ability to apply labels and annotations to the generated StatefulSet from the PrometheusSpec

**Why do we need it?**
Being able to tack on labels to the StatefulSet will allow you to ignore the StatefulSet when using the `--prune` flag and `-l` flag on `kubectl apply` so that the StatefulSet does not get deleted every time you re-apply the kubernetes yaml.

**Comment by brancz** [comment] 2019-06-14 15:46
I felt like we had something like this already. Maybe we’re transferring the labels from the Prometheus object to the statefulset?

**Comment by Devin-Holland** [comment] 2019-06-14 15:50
There is a feature on the Prometheus object to add `podMetaData` which will allow you to add additional labels to the pod, but for the statefulset the labels and from the Prometheus object are directly copied over and you can't add new labels or annotations to it.

**Comment by brancz** [comment] 2019-06-14 18:21
Why can’t you accomplish what you are aiming for by adding the label/annotation you want onto the Prometheus object, hence it gets propagated to the statefulset?

**Comment by Devin-Holland** [comment] 2019-06-14 18:29
So if you run `--purge` on your `kubectl apply` with that label that gets propagated to the stateful set then when kubernetes compares the cluster to your definition yaml it sees the statefulset but it isn't in your definition so it deletes the statefulset.

Example: You have a yaml definition that creates a deployment for Prometheus Operator and then you have a Prometheus object, and a random deployment object in the definition as well. Using Kustomize you apply a common label to all of your objects `purgeMe=true`. You are applying this to a fresh cluster. You want to use `--purge -l purgeMe=true` on your apply so that if you re-apply the yaml without the random deployment in it then the deployment will get deleted since it will have the label but no longer be in your definition yaml. But if you cannot overwrite the purgeMe=true on the stateful set it will get deleted every time you apply the yaml with the purge even though you don't want it to be.

**Comment by brancz** [comment] 2019-06-17 06:52
That makes perfect sense, we should absolutely have he expected behavior here. How does the ReplicaSet do this in relation to the deployment? Or even more fundamentally pods? Ideally I’d want us to have the expected behavior out of the box, without having to do any custom labeling or anything.

**Comment by Devin-Holland** [comment] 2019-06-17 11:50
By default the labels on the Prometheus object are not copied to the ReplicaSet or the Pods so prune will not attempt to remove them. You can add labels to the Pods through the podMetadata on the Prometheus object.

**Comment by brancz** [comment] 2019-06-20 14:19
Sorry for taking so long to reply to this. How about, if the statefulset labels are non-nil, then we don't set the statefulset's labels to the prometheus object's labels?

**Comment by brancz** [comment] 2019-06-20 14:22
I'm wondering about one more thing. The [prune docs say](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/#how-to-delete-objects):

> If an object matches the query, and it does not have a configuration file in the directory, and it has a last-applied-configuration annotation, it is deleted.

But the StatefulSet doesn't get this annotation, why would prune delete it?

**Comment by Devin-Holland** [comment] 2019-06-20 16:23
The stateful set seems to be getting a last-applied-configuration annotation when it gets created because it gets copied from the Prometheus object which gets that annotation automatically applied to it by kubernetes.

As for the statefulset labels being non-nil what do you mean? There is currently no way to interact with the statefulset's labels unless you're talking about adding to the change in my PR to expose statefulset metadata on the prometheus object and then when that is used then only apply those labels not the ones from the prometheus object as well.

**Comment by brancz** [comment] 2019-06-21 08:31
Got it! How about we ignore that annotation when transfering then? Then pruning would work and it's a managed resource anyways, so it's incorrect to be copied. What do you think?

**Comment by Devin-Holland** [comment] 2019-06-21 11:25
I think that's a good solution. I will be on vacation for a week but I'll take a look at making it happen when I get back.

**Comment by brancz** [comment] 2019-06-21 13:01
No worries, enjoy your time off! This sounds like the best solution we could have come up with, very happy with it. Just drop a line here when you get started on it, to avoid someone else picking it up! :)

**Comment by Devin-Holland** [comment] 2019-06-21 15:35
One thing to check still is if kubernetes will automatically apply that label if it's not copied over from the Prometheus object.

**Comment by brancz** [comment] 2019-06-24 06:46
Yes we should check that but to my knowledge this doesn’t happen Server side.

**Comment by juliantaylor** [comment] 2019-12-31 08:31
Any updates on this?
objects created by version 0.34 are still being pruned by kubectl apply because the labels on the prometheus object are transferred to the child runtime generate objects (with the kubectl last-apply annotation)

**Comment by brancz** [comment] 2020-01-07 13:33
To my knowledge this still has to be fixed. Would you like to take this @juliantaylor ?

**Comment by juliantaylor** [comment] 2020-01-07 17:11
yes I can try to provide a PR this week.

**Comment by brancz** [comment] 2020-01-07 19:33
That would be awesome! Thank you!

**Comment by juliantaylor** [comment] 2020-01-08 17:12
posted https://github.com/coreos/prometheus-operator/pull/2944 which fixes the pruning in our deployment pipelines using `kubectl apply --prune -l managementlabel=value`

**Closed** 2020-01-09 18:42 UTC
Labels: kind/feature
