### ISSUE TITLE
Prometheus can't access node-exporter and kube-state-metrics

### ISSUE THREAD

**Issue by sn-x** [coreos/prometheus-operator#2330] opened 2019-01-23 14:36 UTC
**What did you do?**
Deployed kube-prometheus

**What did you expect to see?**
Working node-exporter and kube-state-metrics

**What did you see instead? Under which circumstances?**
Targets get discovered by prometheus, but prometheus cant connect to destination address:port (kube-rbac-proxy). kube-rbac-proxy doesn't bind to  IP:PORT

**Environment**

* Prometheus Operator version: prometheus-operator:v0.27.0

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:04:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind:  kops

**Issue**
The issue started happening after commit 3e7bb3da22597e0a2b7ed0a7b6e0f6a82796eb5c.
kube-rbac-proxy doesn't bind to  IP:PORT

* kube-rbac-proxy log:
I0123 14:09:49.644378   23370 main.go:209] Generating self signed cert as no cert is provided
I0123 14:09:58.544296   23370 main.go:242] Listening securely on 172.20.83.119:9100

 * kube-rbac-proxy container:
~ $ echo $IP
172.20.113.190
~ $ netstat -nlp | grep 9100
netstat: showing only processes with your user ID
tcp        0      0 127.0.0.1:9100          0.0.0.0:*               LISTEN      25306/node_exporter
~ $ 

**Temporary Workaround:**  
Either revert this commit or remove *'--tls-cipher-suites=' + std.join(',', $._config.tlsCipherSuites)* from kube-rbac-proxy from files:
* contrib/kube-prometheus/jsonnet/kube-prometheus/node-exporter/node-exporter.libsonnet
* contrib/kube-prometheus/jsonnet/kube-prometheus/kube-state-metrics/kube-state-metrics.libsonnet

**Comment by brancz** [comment] 2019-01-23 14:38
Duplicate of #2316 . Closing here.

We're working on the real fix, and are trying to get it out the door. We'll let everyone know on #2316, when the fix is available.

**Closed by brancz** 2019-01-23 14:38 UTC

**Comment by brancz** [comment] 2019-01-28 10:48
This has been resolved. Please see: https://github.com/coreos/prometheus-operator/issues/2316#issuecomment-458081838
