### ISSUE TITLE
Race condition / no retries when using EBS volumes for persistent storage

### ISSUE THREAD

**Issue by jescarri** [coreos/prometheus-operator#145] opened 2017-02-14 21:35 UTC
I'm using prometheus-operator:v0.2.3

When I add a prometheus with persisten storage, immediately after apply, the Statefull Set is marked as failed.

Deleting the pod sometimes fixed the problem.

Storage class:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: gp2
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
```

Prometheus:

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: prometheus-dev1
  namespace: prd355-fed
  labels:
    prometheus: prometheus-dev1
spec:
  version: v1.5.2
  externalUrl: http://fed.prd355-fed.dev1.cs.us-east-1.nonprod-tmaws.io
  replicas: 3
  retention: 720h
  resources:
    requests:
      memory: 6000Mi
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 150Gi
```

Logs:

```
Name:		prometheus-dev1-2
Namespace:	prd355-fed
Node:		ip-10-188-160-220.ec2.internal/10.188.160.220
Start Time:	Tue, 14 Feb 2017 20:41:35 +0000
Labels:		app=prometheus
		prometheus=prometheus-dev1
Status:		Pending
IP:
Controllers:	StatefulSet/prometheus-dev1
Containers:
  prometheus:
    Container ID:
    Image:		quay.io/prometheus/prometheus:v1.5.2
    Image ID:
    Port:		9090/TCP
    Args:
      -storage.local.retention=720h
      -storage.local.memory-chunks=1228800
      -storage.local.max-chunks-to-persist=614400
      -storage.local.num-fingerprint-mutexes=4096
      -storage.local.path=/var/prometheus/data
      -config.file=/etc/prometheus/config/prometheus.yaml
    Requests:
      memory:		6000Mi
    State:		Waiting
      Reason:		ContainerCreating
    Ready:		False
    Restart Count:	0
    Readiness:		http-get http://:web/status delay=1s timeout=3s period=5s #success=1 #failure=100
    Volume Mounts:
      /etc/prometheus/config from config (ro)
      /etc/prometheus/rules from rules (ro)
      /var/prometheus/data from prometheus-dev1-db (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-9t6cr (ro)
    Environment Variables:	<none>
  config-reloader:
    Container ID:
    Image:		jimmidyson/configmap-reload
    Image ID:
    Port:
    Args:
      -webhook-url=http://localhost:9090/-/reload
      -volume-dir=/etc/prometheus/config
    Limits:
      cpu:	5m
      memory:	10Mi
    Requests:
      cpu:		5m
      memory:		10Mi
    State:		Waiting
      Reason:		ContainerCreating
    Ready:		False
    Restart Count:	0
    Volume Mounts:
      /etc/prometheus/config from config (ro)
    Environment Variables:	<none>
  rules-reloader:
    Container ID:
    Image:		jimmidyson/configmap-reload
    Image ID:
    Port:
    Args:
      -webhook-url=http://localhost:9090/-/reload
      -volume-dir=/etc/prometheus/rules/
    State:		Waiting
      Reason:		ContainerCreating
    Ready:		False
    Restart Count:	0
    Volume Mounts:
      /etc/prometheus/rules from rules (ro)
    Environment Variables:	<none>
Conditions:
  Type		Status
  Initialized 	True
  Ready 	False
  PodScheduled 	True
Volumes:
  prometheus-dev1-db:
    Type:	PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:	prometheus-dev1-db-prometheus-dev1-2
    ReadOnly:	false
  rules:
    Type:	ConfigMap (a volume populated by a ConfigMap)
    Name:	prometheus-dev1-rules
  config:
    Type:	ConfigMap (a volume populated by a ConfigMap)
    Name:	prometheus-dev1
QoS Class:	Burstable
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From						SubobjectPath	Type		Reason			Message
  ---------	--------	-----	----						-------------	--------	------			-------
  4m		4m		4	{default-scheduler }						Warning		FailedScheduling	[SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "prometheus-dev1-db-prometheus-dev1-2", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "prometheus-dev1-db-prometheus-dev1-2", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "prometheus-dev1-db-prometheus-dev1-2", which is unexpected.]
  4m		4m		1	{default-scheduler }						Normal		Scheduled		Successfully assigned prometheus-dev1-2 to ip-10-188-160-220.ec2.internal
  2m		22s		2	{kubelet ip-10-188-160-220.ec2.internal}			Warning		FailedMount		Unable to mount volumes for pod "prometheus-dev1-2_prd355-fed(f5c221a9-f2f5-11e6-8734-0e683c6b507c)": timeout expired waiting for volumes to attach/mount for pod "prd355-fed"/"prometheus-dev1-2". list of unattached/unmounted volumes=[prometheus-dev1-db]
  2m		22s		2	{kubelet ip-10-188-160-220.ec2.internal}			Warning		FailedSync		Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "prd355-fed"/"prometheus-dev1-2". list of unattached/unmounted volumes=[prometheus-dev1-db]
```

PCV:
```
 kctl  --namespace=prd355-fed describe pvc prometheus-dev1-db-prometheus-dev1-2
Name:		prometheus-dev1-db-prometheus-dev1-2
Namespace:	prd355-fed
Status:		Bound
Volume:		pvc-f5c0dbd7-f2f5-11e6-8734-0e683c6b507c
Labels:		app=prometheus
		prometheus=prometheus-dev1
Capacity:	150Gi
Access Modes:	RWO
```

PV:

```
kctl --namespace=prd355-fed describe pv pvc-f5c0dbd7-f2f5-11e6-8734-0e683c6b507c
Name:		pvc-f5c0dbd7-f2f5-11e6-8734-0e683c6b507c
Labels:		failure-domain.beta.kubernetes.io/region=us-east-1
		failure-domain.beta.kubernetes.io/zone=us-east-1a
Status:		Bound
Claim:		prd355-fed/prometheus-dev1-db-prometheus-dev1-2
Reclaim Policy:	Delete
Access Modes:	RWO
Capacity:	150Gi
Message:
Source:
    Type:	AWSElasticBlockStore (a Persistent Disk resource in AWS)
    VolumeID:	aws://us-east-1a/vol-09914b5e0700b3208
    FSType:	ext4
    Partition:	0
    ReadOnly:	false
```

**Comment by brancz** [comment] 2017-02-14 23:16
The Prometheus Operator relies on the `StatefulSet` controller and `PersistentVolume` controller to provision the actual storage, so if that is racing, then that sounds like an issue that should be taken upstream.

A quick look at the `StatefulSet` controller may have confirmed your suspicion though: https://github.com/kubernetes/kubernetes/blob/da8f68e013b5728fa864e966443e22d073cd235b/pkg/controller/statefulset/stateful_set.go#L120

**Comment by brancz** [comment] 2017-02-15 01:37
Ultimately if this is nothing that is going to be fixed upstream we can fix this by deleting pods if we can tell that the storage is being provisioned and the pod failed due to that reason. This will need some further investigation.

**Comment by fabxc** [comment] 2017-02-15 04:48
In the tests we ran when adding this feature, PVs were attached correctly
on the first try, right?

**Comment by brancz** [comment] 2017-02-15 04:53
I don't recall, but I may get to test this out tomorrow. I remember @Rastusik used a GlusterFS provisioner, which worked, I would expect all storage provisioning to behave the same way once properly configured. Can you comment on this @Rastusik?

**Comment by Rastusik** [comment] 2017-02-15 07:30
@brancz GlusterFS integration works out of the box after my last change, I didn't see any race conditions or suspicious behaviour

**Comment by jescarri** [comment] 2017-02-16 16:52
Thanks for the quick response, how I can help to test this new changes?

**Comment by brancz** [comment] 2017-02-22 15:40
Sorry I seemed to have missed your comment. That was one of our first outside contributions around 3 months ago. They have been available in all latest releases.

**Comment by brancz** [comment] 2017-02-24 15:36
Just tried storage provisioning out on AWS according to #170 and can confirm that it does indeed work without a problem. Maybe something about your cloud provider config is off.

How did you bring up your cluster? kops, kube-aws, bootkube, tectonic-installer, etc.?

**Comment by brancz** [comment] 2017-02-27 10:27
#170 was merged and I can confirm that the documented manifests work with a correctly configured cloud provider (tested using AWS). I will close this for now, if you can reproduce this with the manifests provided in the documentation feel free to reopen this issue.

**Closed by brancz** 2017-02-27 10:27 UTC
