### ISSUE TITLE
Bug in helm chart kube-prometheus/charts/prometheus/templates/servicemonitors.yaml

### ISSUE THREAD

**Issue by xpowerman** [coreos/prometheus-operator#1248] opened 2018-04-24 06:25 UTC
**What did you do?**
Try to install kube-prometheus with one defined servicemonitor in Values using command:
`helm/kube-prometheus --name kube-prometheus --namespace monitoring`
**What did you expect to see?**
Completed installation.

**What did you see instead? Under which circumstances?**
Error: render error in "kube-prometheus/charts/prometheus/templates/servicemonitors.yaml": template: kube-prometheus/charts/prometheus/templates/servicemonitors.yaml:18:30: executing "kube-prometheus/charts/prometheus/templates/servicemonitors.yaml" at <.Values.prometheusLa...>: can't evaluate field prometheusLabelValue in type interface {}

So, when I open kube-prometheus/charts/prometheus/templates/servicemonitors.yaml, I see global values variable **.Values.prometheusLabelValue** inside range cycle. So of course it is wrong, because it try to find it inside provide range **.Values.serviceMonitors**.
```

{{- $app := include "prometheus.name" . -}}
{{- $releaseName := .Release.Name -}}
{{- $chartName := .Chart.Name -}}
{{- $chartVersion := .Chart.Version -}}
{{- $releaseService := .Release.Service -}}
{{- if .Values.serviceMonitors }}
apiVersion: v1
kind: List
items:
{{- range .Values.serviceMonitors }}
  - apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      labels:
        app: {{ $app }}
        chart: {{ $chartName }}-{{ $chartVersion }}
        heritage: {{ $releaseService }}
        prometheus: {{ .Values.prometheusLabelValue | default $releaseName | quote }}
        release: {{ $releaseName }}
        {{- if .serviceMonitorSelectorLabels }}
{{ toYaml .serviceMonitorSelectorLabels | indent 8 }}
        {{- end }}
      name: {{ .name }}
    spec:
      endpoints:
{{ toYaml .endpoints | indent 8 }}
    {{- if .jobLabel }}
      jobLabel: {{ .jobLabel }}
    {{- end }}
    {{- if .namespaceSelector }}
      namespaceSelector:
{{ toYaml .namespaceSelector | indent 8 }}
    {{- end }}
      selector:
{{ toYaml .selector | indent 8 }}
{{- end }}
{{- end }}


```
So, i think it must be fixed using something like   **{{- $prometheusLabelValue := .Values.$prometheusLabelValue -}}**, and use this **$prometheusLabelValue** in range cycle.

**Comment by gianrubio** [comment] 2018-04-25 18:02
closing this as duplicate of #1240

**Closed by gianrubio** 2018-04-25 18:02 UTC
