### ISSUE TITLE
Setting storageSpec wont create a Prometheus instance

### ISSUE THREAD

**Issue by GramozKrasniqi** [coreos/prometheus-operator#2970] opened 2020-01-23 21:59 UTC
**What happened?**
Setting storageSpec for Prometheus dosent create the prometheus instance

**Did you expect to see some different?**
Prometheus instance is created and also PV and PVC

**How to reproduce it (as minimally and precisely as possible)**:
- Install prometheus-operator `0.35.0` or `0.34.0`
- Use the following CRDs
```
kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/v0.34.0/example/prometheus-operator-crd/alertmanager.crd.yaml

kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/v0.34.0/example/prometheus-operator-crd/prometheus.crd.yaml

kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/v0.34.0/example/prometheus-operator-crd/prometheusrule.crd.yaml

kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/v0.34.0/example/prometheus-operator-crd/servicemonitor.crd.yaml

kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/v0.34.0/example/prometheus-operator-crd/podmonitor.crd.yaml
```

**Environment**

**Prometheus Operator version**: `0.35.0` & `0.34.0`
 
**kubectl version**

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"1da9875156ba0ad48e7d09a5d00e41489507f592", GitTreeState:"clean", BuildDate:"2019-11-14T05:19:20Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**helm version**
```
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

* Kubernetes cluster kind:

    `AKS`

* Manifests:

**Prometheus manifest**

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  creationTimestamp: "2020-01-23T21:47:03Z"
  generation: 1
  labels:
    app: prometheus-operator-prometheus
    chart: prometheus-operator-8.5.14
    heritage: Helm
    release: operators
  name: operators-prometheus-opera-prometheus
  namespace: operators
  resourceVersion: "38455"
  selfLink: /apis/monitoring.coreos.com/v1/namespaces/operators/prometheuses/operators-prometheus-opera-prometheus
  uid: e427d5a5-3e29-11ea-a6cf-6e7e41673074
spec:
  alerting:
    alertmanagers:
    - name: operators-prometheus-opera-alertmanager
      namespace: operators
      pathPrefix: /
      port: web
  baseImage: quay.io/prometheus/prometheus
  enableAdminAPI: false
  externalUrl: http://operators-prometheus-opera-prometheus.operators:9090
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  podMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      release: operators
  portName: web
  replicas: 1
  retention: 45d
  retentionSize: 25GB
  routePrefix: /
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      app: prometheus-operator
      release: operators
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: operators-prometheus-opera-prometheus
  serviceMonitorNamespaceSelector:
    any: true
  serviceMonitorSelector:
    any: true
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          request:
            storage: 35Gi
        storageClassName: default
  version: v2.13.1
```

* Prometheus Operator Logs:

I find it really interesting that this whole thing is happening without any logs being outputted (silent mode)

```
caller=operator.go:1084 component=prometheusoperator msg="sync prometheus" key=operators/operators-prometheus-opera-prometheus
```

**Anything else we need to know?**:

**kubectl get storageclass**
```
NAME                          PROVISIONER                    AGE
default (default)          kubernetes.io/azure-disk   3h15m
managed-premium     kubernetes.io/azure-disk   3h15m
``` 

As soon as i remove the storageSpec and deploy it it will create the Prometheus instance (of course with emptyDir).

**Comment by brancz** [comment] 2020-01-24 13:24
This is likely a duplicate of https://github.com/coreos/prometheus-operator/issues/2950

**Comment by brancz** [comment] 2020-01-24 13:25
cc @simonpasquier i think you’re looking into this right?

**Comment by GramozKrasniqi** [comment] 2020-01-24 14:33
Just a side note maybe important the same behavior is experienced with k8s 1.13.12 & 1.14.8 on AKS

**Comment by simonpasquier** [comment] 2020-01-24 15:24
@brancz hmm no, maybe @pgier?

**Comment by brancz** [comment] 2020-01-24 16:08
I'm starting to deduplicate, because this is getting out of control. Closing as duplicate of #2950.

**Comment by pgier** [comment] 2020-01-24 23:27
Reopening because I'm not sure this is a duplicate of #2950.  What I'm seeing is that the storage config is not correctly copied into the statefulset.  @GramozKrasniqi can you verify that the generated prometheus stateful set does not include the `resources` portion of the volumeClaimTemplate?
```yaml
       resources:
          request:
            storage: 35Gi
```
Also if you do a `kubectl describe` on the stateful set that might confirm the reason the pods are not being created.

**Comment by pgier** [comment] 2020-01-25 05:58
I think the problem here is a typo, `request` should be plural `requests`.  Feel free to reopen this issue the spelling change doesn't fix the problem.

**Closed by pgier** 2020-01-25 05:58 UTC
Labels: kind/bug

**Comment by GramozKrasniqi** [comment] 2020-01-25 11:31
@pgier yep sorry that was the typo problem.
Thank you for your help :)
