### ISSUE TITLE
HA Prometheus Operator

### ISSUE THREAD

**Issue by tushar00jain** [coreos/prometheus-operator#2491] opened 2019-03-15 08:11 UTC
There is nothing said about the High Availability of the operator itself

https://github.com/coreos/prometheus-operator/blob/master/Documentation/high-availability.md

This states the high availability of Prometheus and Alert Manager but what about the operator itself? Is there no need for making the operator highly available? Will you ever support having operator replica count greater than 1?

**Comment by brancz** [comment] 2019-03-15 10:49
We would need to implement leader election for this, which is generally possible, but not yet implemented.

**Comment by tushar00jain** [comment] 2019-03-15 11:06
please, it's painful to see `replicas: 1` hard coded in all the operators so far

**Comment by brancz** [comment] 2019-03-15 14:05
We're not using the operator framework, prometheus-operator far pre-dates the operator sdk.

**Comment by RiRa12621** [comment] 2019-03-15 14:37
Isn't the operator generally stateless?
If so is there any actual need to have that highly available?
If you lose your operator instance for a short time until the new pods is spawned, nothing should happen except that new rules and prometheus are not picked up immediately.

**Comment by brancz** [comment] 2019-03-15 14:43
That's exactly why we haven't really put any effort into it @RiRa12621. You're absolutely right.

**Comment by tushar00jain** [comment] 2019-03-15 15:56
is that to say stateless applications don't need HA? i don't think so

I guess it's not that bad because there won't be any considerable number of requests to operator to make a difference in it's operation and that it's probably not really doing anything for the large part

but consider a bad timing when the operator needs to be engaged and it's not available because kubernetes is rescheduling the one and only pod, either way considering the benefit i agree it's not worth prioritising

**Comment by RiRa12621** [comment] 2019-03-15 16:35
I think the last part of what you're said is the main fact here @tushar00jain: it's a lot of effort for relatively low effect.
yes of course I also like HA for all the things but sometimes it's just not worth it.

**Comment by tushar00jain** [comment] 2019-03-15 17:09
totally agree, feel free to close this

**Comment by tushar00jain** [comment] 2019-03-15 17:14
it just seemed strange and surprising to me that there is so much attention around operators but the operator itself is not HA because i too like everything HA

maybe red hat will bring this to notice in the operator framework 🤔

**Comment by metalmatze** [comment] 2019-03-18 12:50
As earlier said, it isn't that big of a deal if the operator is missing for 15s.
I'll close this issue for now, feel free to continue to comment, but it's not something that we will tackle on the near future.

**Closed by metalmatze** 2019-03-18 12:50 UTC
Labels: kind/enhancement

**Comment by bgagnon** [comment] 2020-09-16 20:38
We've run into this.

When prometheus-operator is crash looping, it might become unavailable, but the pod will continue running on the same node with a restarting container. There is nothing that will magically "heal" this prometheus operator on the cluster. The idea that "15 seconds" or "30 seconds" is an upper bound on unavailability is inaccurate, IMO.

For such situation, HA through leader election would have come in handy:
* one active replica, one hot standby replica
* only one replica holds the leader lock
* if the lock cannot be renewed for any reason, the hot standby takes over
* the damaged replica still needs healing, but the operator's duties are still being fulfilled until that happens

In our multi-tenant platform, we provide monitoring-as-a-service to our namespace tenants exclusively via the Prometheus Operator CRDs. Availability of the Operator is directly linked to the availability of this service.

**Comment by RiRa12621** [comment] 2020-09-16 20:52
From my perspective if any pod goes crashlooping and stays that way, be it prometheus-operator or whatever other app you have, you need to solve the root cause and not the symptom.
In case someone were to implement HA (PRs welcome, I assume), you would still need to manually interact with the cluster in your case since as you said, the pod is not coming back to a normal state on its own.
Your alerting/monitoring does not stop working if the operator itself is crashlooping so you'll notice that it's happening.
If you implement HA you just have more time to look into the root cause for this permanent failure.
I agree that in this case the timings I assumed earlier are probably not true but what reasons are there for a stateless pod to keep crashlooping?
If we exclude something particularly wrong with prometheus operator pod, because then HA wouldn't save you, that means something is not right with your cluster or that specific node(in case you forced the deployment onto that node using labels).
In either way you will sooner or later have significantly bigger issues than the prometheus pod.
If it's limited to the node, whatever else is running on there will have similar issues an it needs interaction.
if it's a cluster level issues, that definitely needs manual interaction.
