### ISSUE TITLE
Basic auth fails due to introduction of newline

### ISSUE THREAD

**Issue by gokart23** [coreos/prometheus-operator#1568] opened 2018-07-03 14:31 UTC
**What did you do?**
I was working on deploying a ServiceMonitor for an endpoint which required authentication. The configuration was along the lines of:
```
apiVersion: v1
kind: Secret
metadata:
  name: endpoint-creds
  namespace: monitoring
data:
  username: 'dXNlcm5hbWUK' # username
  apitoken: 'cGFzc3dvcmQK' # password
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: svcmon
  name: svcmon
  namespace: monitoring
spec:
  endpoints:
  - port: access
    path: '/endpoint'
    params:
      format: 
      - prometheus
    interval: '30s'
    basicAuth:
      username: 
        name: endpoint-creds
        key: username
      password:
        name: endpoint-creds
        key: apitoken
  namespaceSelector:
    matchNames:
      - ns-service
  selector:
    matchLabels:
        app: rbin-service
```
I also tried setting up the secret with yaml block stripping, but observed the same results.

**What did you expect to see?**
I expected prometheus to collect metrics by polling the endpoint using the provided credentials

**What did you see instead? Under which circumstances?**
The endpoint repeatedly returned 401 (Unauthorized) status code. On inspecting the object registered with prometheus, I found that the username and password were successfully being extracted:
```
$ kubectl get secret prometheus-k8s -n monitoring -ojson | jq -r '.data["prometheus.yaml"]' | base64 -d | grep svcmon -A 20
- job_name: monitoring/svcmon/0
  honor_labels: false
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - ns-service
  scrape_interval: 30s
  metrics_path: /endpoint
  params:
    format:
    - prometheus
  basic_auth:
    username: |
      username
    password: |
      password
...
```
On inspecting the actual request headers being received by the endpoint, I observed that the auth header contained a newline between the username and password:
```
Authorization: Basic dXNlcm5hbWUKOnBhc3N3b3JkCg==
```
the credentials of which decode to:
```
username
:password
```

**Environment**

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```
* Prometheus operator version
```
prometheus-operator:v0.19.0
```
* Kubernetes cluster kind: kubeadm

* Prometheus Operator Logs: Operator logs do not reflect anything out of the ordinary

**Comment by brancz** [comment] 2018-07-03 14:45
I think you forgot to paste the `ServiceMonitor` you wanted to share :slightly_smiling_face: .

**Comment by gokart23** [comment] 2018-07-03 14:47
@brancz sorry about that - updated :slightly_smiling_face:

**Comment by brancz** [comment] 2018-07-03 15:26
Thanks for the thorough report! Could you also let us know which version of Prometheus this is?

**Comment by brancz** [comment] 2018-07-03 16:11
I was able to reproduce this with a minimal Prometheus configuration, but I'm afraid this is a Prometheus bug, not a Prometheus Operator bug, I will go ahead and open a bug there with a minimal config to reproduce. Thanks a lot for opening this issue!

**Comment by brancz** [comment] 2018-07-03 16:34
I take that back, I think Prometheus is doing everything correctly. The yaml spec says that when a string field is defined with the `|` then the string has a new line at the end of it, so we are marshaling this incorrectly.

**Comment by anandsinghkunwar** [comment] 2018-07-04 06:38
I think it should have `|-` and not `|`. Also, I am not sure why others haven't faced this yet.

**Comment by rsingh2411** [comment] 2018-07-04 13:13
Recieving the same issue, 401 unauthorized.  @anandsinghkunwar by chance is there any workaround for this issue.

**Comment by anandsinghkunwar** [comment] 2018-07-04 13:21
Don't know a way to use prom-operator and use basic auth currently.

**Comment by brancz** [comment] 2018-07-04 14:01
I tried an end to end example and I think this is actually about how you generate your `Secret` object. Make sure that when you are encoding things in base64, that the input does not actually contain a line break.

```
# this makes sure that there is no line break at the end
$ echo -n "username" | base64
dXNlcm5hbWU=

# this is wrong, it has a line break at the end
$ echo "username" | base64 
dXNlcm5hbWUK
```

Comparing this to the values that you shared, it looks like your `Secret` was just created with line breaks, so everything is actually working as intended.

**Comment by rsingh2411** [comment] 2018-07-05 09:29
Thanks, @brancz , The suggestion worked, basic auth is working and scraping targets is working

**Comment by brancz** [comment] 2018-07-05 12:54
I'm going to close this here, but feel free to keep commenting or open a new issue should you run into any other problem!

**Closed by brancz** 2018-07-05 12:54 UTC
Labels: kind/bug
