### ISSUE TITLE
Change the k8s URL for IPv6 uses

### ISSUE THREAD

**Issue by valentin2105** [coreos/prometheus-operator#703] opened 2017-10-19 22:57 UTC
**What did you do?**

I try to change the k8s API Url for the helm/prometheus chart, but It's always go to 10.32.0.1.

How can I inject `KUBERNETES_SERVICE_HOST` to the `kind: Prometheus` resource but It doesn't work. 

My cluster use only IPv6 so the default 10.32.0.1 is, for sure, unreachable. 

* Kubernetes version information:

v1.8.1, Calico, IPv6 only, Debian 9, Prometheus-Operator charts 0.0.4

**Comment by brancz** [comment] 2017-10-20 06:21
The charts are quite work in progress I recommend using them off of this repo. Prometheus simply discovers the apiserver IP(s) from the Endpoints objects provided by Kubernetes, which is in the default namespace. I don’t think this is an issue with the Prometheus Operator. Can you have the output of:

kubectl get endpoints kubernetes -oyaml

**Comment by valentin2105** [comment] 2017-10-22 22:01
Hi @brancz , 
My Endpoint is correctly the Kube-APIserver IPv6, but Prometheus use the service instead, 

How to change that ? 

```
time="2017-10-22T22:00:51Z" level=error msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:181: Failed to list *v1.Pod: Get https://10.32.0.1:443/api/v1/namespaces/monitoring/pods?resourceVersion=0: dial tcp 10.32.0.1:443: connect: network is unreachable" component="kube_client_runtime" source="kubernetes.go:75"
time="2017-10-22T22:00:51Z" level=error msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:181: Failed to list *v1.Pod: Get https://10.32.0.1:443/api/v1/namespaces/monitoring/pods?resourceVersion=0: dial tcp 10.32.0.1:443: connect: network is unreachable" component="kube_client_runtime" source="kubernetes.go:75"
time="2017-10-22T22:00:51Z" level=error msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:180: Failed to list *v1.Service: Get https://10.32.0.1:443/api/v1/namespaces/monitoring/services?resourceVersion=0: dial tcp 10.32.0.1:443: connect: network is unreachable" component="kube_client_runtime" source="kubernetes.go:75"
```

**Comment by brancz** [comment] 2017-10-23 06:55
I see, yes this is actually in upstream Prometheus, not the Prometheus Operator. I would recommend opening an issue there so that the other maintainers also have visibility of this issue.

Nonetheless, I think I've already discovered the problem. Client-go seems to default to that IP, but there is a comment, that it _should_ default to the cluster DNS. This is probably what we should do here, fix client-go, and then update it in Prometheus.

RE: https://github.com/kubernetes/client-go/blob/82aa063804cf055e16e8911250f888bc216e8b61/rest/config.go#L317

**Comment by valentin2105** [comment] 2017-10-23 22:18
Thanks for your answer. 
Do you know if it's possible to give the ENV `KUBERNETES_SERVICE_HOST` to the pod created by the `kind: Prometheus` yml file ?  I have try the `env:` key but it doesn't work.. 
(It work for deployment, rc, pod ...)

**Comment by incognick** [comment] 2018-03-27 22:17
I'm running into this as well. Any updates here?

**Comment by brancz** [comment] 2018-03-28 07:45
`KUBERNETES_SERVICE_HOST` is set by Kubernetes, so we can't override it. I've contacted some client-go maintainers, to see what our options are.

**Comment by incognick** [comment] 2018-03-28 08:45
Thanks for responding so quickly. 

What if the prometheus CRD spec provided environment variables that we could pass along to the Prometheus container spec here? https://github.com/coreos/prometheus-operator/blob/7ecc95274d1c4a68b97ab97d9f822f29fb0767c0/pkg/prometheus/statefulset.go#L575

**Comment by brancz** [comment] 2018-03-28 09:12
So it turns out, that this is actually all working as intended, it's just that the Kubernetes Services/Endpoints objects are not using IPv6 (yet). There is work upstream to do this, but there is no bug here, so I will close this.

The code where the kubelet adds these flags is: https://github.com/kubernetes/kubernetes/blob/012b085ac870d359131f4251213bf2fff1d15aa0/pkg/kubelet/envvars/envvars.go#L46

Once the ClusterIP in the Service object is an IPv6 address it will just start to work, no need to modify the Prometheus Operator or Prometheus.

**Closed by brancz** 2018-03-28 09:12 UTC

**Comment by incognick** [comment] 2018-03-28 12:20
My use case is not related to IPv6. I’m previewing AWS’ EKS and the masters are at a public endpoint so any pods trying to reference the API, fail. Can you confirm my suggestion above? I have created a fork to try this out today. Thanks!

**Comment by brancz** [comment] 2018-03-28 12:42
My guess is that that would require overriding the Kubernetes API endpoint used in the Prometheus config, rather than via an environment variable.

**Comment by incognick** [comment] 2018-03-28 17:50
You are correct.  The kubelet keeps overriding the environment vars. I tried making my own prometheus container.  I'll try the config route.  Thanks!
