### ISSUE TITLE
How to configure alertmanager to use a forward proxy?

### ISSUE THREAD

**Issue by eugene-chow** [coreos/prometheus-operator#399] opened 2017-06-08 06:19 UTC
Hi guys, I installed prometheus-operator on k8s 1.6.4. Outgoing traffic from the cluster goes thru a corporate proxy.

Based on [this issue](https://github.com/prometheus/alertmanager/issues/628), it seems like alertmanager can pick up `https_proxy` from the environment. However, the [docs](https://coreos.com/operators/prometheus/docs/latest/api.html) don't indicate how to configure it in the alertmanager manifest.

What's your suggestion to pass the `https_proxy` environment vars to alertmanager? Thanks! :)

**Comment by brancz** [comment] 2017-06-08 14:06
I realize this is something that is required, but IIRC it is merely a coincidence that the environment variable works for the Alertmanager. I would like to make sure that we have a lasting solution here.

**Comment by eugene-chow** [comment] 2017-06-08 14:34
I’ve scanned thru Alertmanager’s logs and nothing is mentioned about configuring a proxy. For the time being, is it possible to inject the proxy env vars into the Alertmanager manifest?

**Comment by brancz** [comment] 2017-06-08 14:47
The problem is that it is not clear whether the proxy should be configured via the configuration file or otherwise. Typically all Prometheus projects are _only_ configured via configuration file, and this case that the proxy is usable via environment variable is pure coincidence, because of how the underlying http client works. I would like to avoid introducing things in the Alertmanager/Prometheus TPR that is unclear whether it may be deprecated soon. It feels like the http proxy config should be a part of the Alertmanager receiver configurations.

Luckily all maintainers of the Prometheus Operator are Alertmanger maintainers, so we can relatively easily take this upstream if necessary.

**Comment by eugene-chow** [comment] 2017-06-08 14:53
I understand the importance of doing this the right way. Do you mean that there isn’t a way to pass the env vars to Alertmanager in Prometheus-operator? I’m seeking a temporary quick fix while we work out the correct way for the long haul.

**Comment by brancz** [comment] 2017-06-08 14:55
There is currently no way to do this with the Prometheus Operator, as you can't control the StatefulSet that the Prometheus Operator creates for the Alertmanager cluster. If that is indeed something you need right away, I would suggest to not use the Prometheus Operator for that Alertmanager cluster and configure it manually right now. It is definitely something we need to address though.

**Comment by eugene-chow** [comment] 2017-06-08 14:58
Thanks for the confirmation :) I’ll open a ticket with the Alertmanager folks and see what they say.

**Comment by brancz** [comment] 2017-06-08 14:59
Go for it! As I said pretty much the same folk as here, so talk to you there :smile:

**Comment by luisyonaldo** [comment] 2018-02-16 13:49
https://github.com/prometheus/alertmanager/pull/1222

**Comment by brancz** [comment] 2018-02-16 16:46
Thanks for pointing out @luisyonaldo. With that patch, this is now possible. Closing here :tada:

**Closed** 2018-02-16 16:46 UTC

**Comment by jolson490** [comment] 2018-03-21 17:03
The latest [release of prometheus-operator](https://github.com/coreos/prometheus-operator/releases) is `v0.17.0`, which [uses](https://github.com/coreos/prometheus-operator/blob/v0.17.0/contrib/kube-prometheus/manifests/alertmanager/alertmanager.yaml#L9) `v0.14.0` of [alertmanager](https://github.com/prometheus/alertmanager).
The new `http_config.proxy_url` functionality wasn't introduced to alertmanager until after `v0.14.0` - it is present in `v0.15.0-rc.0`, but between those two versions of alertmanager there were non-backwards-compatible changes made to the alertmanager flags (so I can't just simply use `v0.17.0` of prometheus-operator with `v0.15.0-rc.0` of alertmanager). So I'm kinda feeling stuck waiting for a new version of prometheus-operator to come out.
So in the meantime...

(Regarding what @brancz  said above about how "you can't control the StatefulSet that the Prometheus Operator creates for the Alertmanager cluster", by looking at the [prometheus-operator/pkg/alertmanager/statefulset.go](https://github.com/coreos/prometheus-operator/blob/v0.17.0/pkg/alertmanager/statefulset.go) code, I can see he's right.)

I know it would be an unsupported temporary hack to set the http_proxy environment variable in the alertmanager pod, but if anyone knows of a way to do that, could you please tell me how? I tried doing the following, but the env var only seems to actually get set (and stay set) some of the time - here's an e.g. of when it didn't work (i.e. the grep shows that `http_proxy` wasn't actually set):
```
core@myIp ~ $ kubectl -n monitoring set env statefulset/alertmanager-main --all "http_proxy=http://192.168.237.68:8080"
statefulset "alertmanager-main" env updated
core@myIp ~ $ kubectl --namespace=monitoring exec -ti alertmanager-main-0 -c alertmanager env | grep -i prox
core@myIp ~ $
```

Background info: The K8s cluster that I'm running [kube-prometheus](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/hack/cluster-monitoring/self-hosted-deploy) on is inside a "closed" cluster (which is not directly available to the internet) that can only reach out to the internet via our proxy. So in order for notifications sent from alertmanager to reach our HipChat room (via the default value of `https://api.hipchat.com/` for 'hipchat_api_url'), I need to be able to tell alertmanager to use our proxy.

**Comment by brancz** [comment] 2018-03-21 18:01
We are already implementing support for v0.15 for the alertmanager and a new release is around the corner, your problem will soon be solved :)

**Comment by jolson490** [comment] 2018-03-26 17:30
Awesome, thanks @brancz . Just curious, is there anywhere I can look online where a rough guess has been shared as to when the next release of prometheus-operator will be coming out?

In the mean time, I've found that sometimes i need to run the aforementioned `kubectl set env` command several times in order for it to work, but even when it does work then after some amount of time (just a guess: perhaps when the alertmanager pod restarts / or when K8s moves the pod to another node) I've noticed the environment variable will no longer be set in that pod. If by chance anyone has any suggestions for this, I'd be all ears. Though no worries if we just wait til the new release (which will introduce `http_config.proxy_url`).

**Comment by anandsinghkunwar** [comment] 2018-04-24 07:50
@brancz Any hack for injecting environment variables into the pod? Also, do you have an ETA on the next release of the operator?

**Comment by brancz** [comment] 2018-04-24 07:56
The latest release of the prometheus operator already supports the Alertmanager v0.15 series which supports this.

**Comment by azizzoaib786** [comment] 2018-07-25 13:13
based on documentation .. inside alertmanager.yml file, we can define as below:

global:
hipchat_api_url: 'https://company.hipchat.com'
http_config:
proxy_url: 'http://(IP):3128'
