### ISSUE TITLE
Alert K8SApiServerLatency triggering 

### ISSUE THREAD

**Issue by gianrubio** [coreos/prometheus-operator#343] opened 2017-05-05 09:18 UTC
The alert `K8SApiServerLatency` is strangely triggering to all my clusters. I checked my apiservers and etcd instances and looks they're smoothly running without latency or load issue.  

## Alert
```
ALERT K8SApiServerLatency
  IF histogram_quantile(0.99, sum(apiserver_request_latencies_bucket
{verb!~"CONNECT|WATCHLIST|WATCH"}) 
WITHOUT (instance, node,resource)) / 1000000 > 1
  FOR 10m
  LABELS {service="k8s", severity="warning"}
  ANNOTATIONS {description="99th percentile Latency 
for {{ $labels.verb }} requests to the kube-apiserver is higher
 than 1s.", summary="Kubernetes apiserver latency is high"}
```

## Value > 1 are triggering
![screen shot 2017-05-05 at 11 01 11](https://cloud.githubusercontent.com/assets/5694860/25739447/310c3c12-3182-11e7-991a-7ff0fa6e4a88.png)

## What's wrong?
Analysing this alert it's not comparing verb `WATCHLIST` but it is for verb `LIST`. As we can see in the graph below the latency for verb `WATCHLIST` is exactly the same for `LIST`.  I'm here to heard if it's something wrong on my environment or if other users has the same behaviour, I have the same values in 2 clusters.

## Latency with all verbs
![screen shot 2017-05-05 at 11 00 25](https://cloud.githubusercontent.com/assets/5694860/25739446/30f17d64-3182-11e7-9ddc-51213f5d5497.png)

**Comment by brancz** [comment] 2017-05-05 09:34
Very interesting! I wouldn't expect this behavior, I'll check as well.

**Comment by brancz** [comment] 2017-05-05 12:16
I'm not seeing the same behavior:

![screenshot from 2017-05-05 14-14-24](https://cloud.githubusercontent.com/assets/4546722/25745027/49e9c7b6-319d-11e7-9dc3-65592c777e55.png)
![screenshot from 2017-05-05 14-14-01](https://cloud.githubusercontent.com/assets/4546722/25745026/49e8fcbe-319d-11e7-890b-d7ac4f2a518f.png)

`LIST` seems to behave normally in my cluster.

**Comment by gianrubio** [comment] 2017-05-05 12:21
This is a real cluster under production or only a minikube?

**Comment by brancz** [comment] 2017-05-05 12:30
This is a multi node cluster on AWS (1.6.2), but it does not serve any production applications. That said it is however running all CoreOS Tectonic components which do a lot of `LIST`/`WATCH`/`LISTWATCH` actions on the apiserver.

**Comment by gianrubio** [comment] 2017-05-08 09:45
Because this issue it's not related to operator I'll close for now

**Comment by ohaiwalt** [comment] 2017-05-19 17:28
Also experiencing this in two clusters (one prod, one not) after upgrading from operator `v0.2.1` to `v0.9.0`, Prometheus `v1.5.1` to `v1.6.2`, and transitioned from custom config to using ServiceMonitors. Both clusters are 3-master on AWS, with >15 nodes each.

Did you happen to learn any more @gianrubio?

**Comment by ohaiwalt** [comment] 2017-05-20 00:52
Curiously the value is also 8 for me using the above query

**Comment by ese** [comment] 2017-05-31 10:49
We are facing something like this with verb PROXY. Should it be added to the filter? @brancz

**Comment by brancz** [comment] 2017-05-31 13:37
@ese that sounds reasonable, I'll add it.

**Comment by brancz** [comment] 2017-06-12 12:24
The PROXY verb has been added and the PR is merged. Closing here.

**Closed by brancz** 2017-06-12 12:24 UTC

**Comment by slintes** [comment] 2017-08-25 08:28
Did somebody find out where that value "8" for some list actions is coming from? We have the same problem...

**Comment by brancz** [comment] 2017-08-25 08:34
8 is the maximum bucket size, so essentially the number of requests larger than 8 seconds, and in 99% quantile if there are enough requests that fall into that bucket then it's the value you get alerted on.

**Comment by slintes** [comment] 2017-08-25 09:14
thanks! Still strange that I can't reproduce these slow list requests with kubectl, that's always way faster than 8 seconds... :/

**Comment by pete0emerson** [comment] 2017-08-31 16:58
This one is biting us, too. Performance is fine AFAICT.

```
$ kubectl  describe pod prometheus-k8s-0 --namespace=monitoring | grep quay
    Image:              quay.io/prometheus/prometheus:v1.7.0
    Image ID:           docker-pullable://quay.io/prometheus/prometheus@sha256:7a34a40d08ed21456bf0644ed247ea1af853d423aaaf26758bc9448e712637ff
    Image:              quay.io/coreos/prometheus-config-reloader:v0.0.2
    Image ID:           docker-pullable://quay.io/coreos/prometheus-config-reloader@sha256:9ea705b2234f7deea22058a00ea46a303087828bde579b37255a590e8c0f4eca
```

![screen shot 2017-08-31 at 9 56 04 am](https://user-images.githubusercontent.com/296757/29935166-b1f47b98-8e32-11e7-9899-6efe7c23d054.png)

It's only the GET verb, pegged at `8` like others.

**Comment by brancz** [comment] 2017-09-04 09:45
@pete0emerson in your case it seems to be the log resource endpoint, which can naturally take a long time, so we should just ignore that one, especially as it also allows following/streaming so it can actually be infinitely long.

@slintes the Kubernetes components themselves are doing requests to the apiserver, so those latencies are not only coming from kubectl alone. Could you post the ones that are firing for you? It's likely that they just have to be ignored, like the logs resource, as we can't tell by the latency whether something is wrong.

**Comment by slintes** [comment] 2017-09-04 14:06
at this moment we have this for LIST on persistentvolumes, persistentvolumeclaims, statefulsets, ingresses, secrets, endpoints, pods, storageclasses, services and configmaps. So many but not all resources. I solved this by using the 90% quantile instead of 99%, then everything is fine. But of course the alert will be triggered later when there is a real problem...

**Comment by brancz** [comment] 2017-09-04 14:27
Interesting. How many objects do you have? Your solution might be perfectly valid, maybe we even just need to explicitly alert on list actions separately as they have different SLOs than the other endpoints, that handle only single objects.

**Comment by slintes** [comment] 2017-09-04 21:30
Sorry, missed your reply.
There are only very few objects in that cluster, less than 50 pods etc., which makes it even more strange.
Handling list actions separately sounds like a good idea :)

**Comment by mindw** [comment] 2017-10-27 11:08
A naive question -  isn't `apiserver_request_latencies_bucket`a counter? if so shouldn't it 
be `sum(rate(apiserver_request_latencies_bucket{verb!~"CONNECT|WATCHLIST|WATCH"})) ...`?

BTW 👍 on excluding list. seeing this on production cluster with 300 pods for `get pods`.

**Comment by brancz** [comment] 2017-10-27 12:33
The multiple bucket counters (and a bit more) make up a histogram, which describes the latency distribution as raw data, and then quantiles are calculated at query time.
