### ISSUE TITLE
node-exporter Pod IP instead of NodeIP in default Grafana Node's dashboard

### ISSUE THREAD

**Issue by zytek** [coreos/prometheus-operator#1285] opened 2018-04-30 09:45 UTC
**What did you do?**

Pure default hack/cluster-monitoring/deploy from current master (72b2e6847dec58269dfe4950097344155f8bc6cf)

* Kubernetes version information and environment

`
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-13T22:27:55Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.11", GitCommit:"1df6a8381669a6c753f79cb31ca2e3d57ee7c8a3", GitTreeState:"clean", BuildDate:"2018-04-05T17:16:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
`

AWS based cluster with kops kops

**Issue**
Under "Nodes" daahboard in Grafana the "server" selector lists servers as node-exporter pod IP addresses instead of node identifiers (I would expect either EC2 IP addresses or hostnames).

Pod IP addresses are ephemeral so after node-exporter "redeploy" they would change (AFAIK).

I'm not sure but I believe this worked fine some ~month ago when I was first checking out prometheus operator.

```
k describe pod node-exporter -n monitoring | grep -E "Node:|IP"
Node:           ip-10-10-49-20.eu-west-1.compute.internal/10.10.49.20
IP:             100.96.1.41
Node:           ip-10-10-53-196.eu-west-1.compute.internal/10.10.53.196
IP:             100.96.3.89
Node:           ip-10-10-50-75.eu-west-1.compute.internal/10.10.50.75
IP:             100.96.2.54
```
![screen shot 2018-04-30 at 11 44 26](https://user-images.githubusercontent.com/3696278/39422001-df212024-4c6b-11e8-8c9a-1a72a969f292.png)

**Comment by brancz** [comment] 2018-04-30 12:48
Duplicate of #744, this will be addressed with #1279 as the dashboard changes in there do this, closing this as #744 is already tracking this.

**Closed by brancz** 2018-04-30 12:48 UTC
