### ISSUE TITLE
pod prometheus-operator cannot run

### ISSUE THREAD

**Issue by junsionzhang** [coreos/prometheus-operator#2124] opened 2018-11-13 08:21 UTC
in the k8s ver 1.11.4 , ' kubectl create -f   .  '   runs under folder  prometheus-operator/contrib/kube-prometheus/manifests . every pod works fine  but the status of pod  prometheus-adapter is  ' CrashLoopBackOff', command 'kubectl log' gets the logs as follow, 

```
W1113 08:19:06.133423       1 authentication.go:245] Unable to get configmap/extension-apiserver-authentication in kube-system.  Usually fixed by 'kubectl create rolebinding -n kube-system ROLE_NAME --role=extension-apiserver-authentication-reader --serviceaccount=YOUR_NS:YOUR_SA'
F1113 08:19:06.133470       1 adapter.go:206] unable to install resource metrics API: open /tmp/client-ca-file966259614: no such file or directory
```

**Comment by brancz** [comment] 2018-11-13 12:39
This is a duplicate of #2116 .

You need to force the image to be re-downloaded there was a mistake when publishing the image.

**Comment by metalmatze** [comment] 2018-11-14 16:39
I'll close this issue. Feel free to comment nevertheless, if you still have problems.

**Closed by metalmatze** 2018-11-14 16:39 UTC
