### ISSUE TITLE
Support for monitoring external HTTPs targets

### ISSUE THREAD

**Issue by optiomas** [coreos/prometheus-operator#1114] opened 2018-03-19 17:12 UTC
**What did you do?**

In order to monitor a service external to the cluster, I followed your example at https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/docs/Monitoring%20external%20etcd.md.

**What did you expect to see?**

A successfully scraped target.

**What did you see instead? Under which circumstances?**

Prometheus reports the target returns a 404. The reason for this is that setting the `tlsConfig.serverName` doesn't set a `Host` header in the [Prometheus HTTP Client](https://github.com/prometheus/prometheus/blob/master/util/httputil/client.go#L173).

Since the endpoint is explicitly defined as an IP address, and the target is only exposed over HTTPs, the Host header needs to be set.

Alternatively, the `ServiceMonitor` could be changed to support `Services` of the type `externalName`: https://akomljen.com/kubernetes-tips-part-1/

**Environment**

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:51:54Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.7+coreos.0", GitCommit:"768e049ab5230010251f30475e0e785e2e999566", GitTreeState:"clean", BuildDate:"2018-01-18T00:17:18Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

tectonic-installer

* Manifests:

```
kind: Endpoints
apiVersion: v1
metadata:
  labels:
    app: jira
  name: jira
  namespace: production
subsets:
  - addresses:
    - ip: ELIDED
    ports:
    - name: https
      protocol: TCP
      port: 443
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: jira
  name: jira
  namespace: production
spec:
  jobLabel: app
  endpoints:
    - port: https
      interval: 30s
      path: /plugins/servlet/prometheus/metrics
      scheme: https
      params:
        token: [ELIDED]
      tlsConfig:
        serverName: "ELIDED"
  namespaceSelector:
    matchNames:
      - production
  selector:
    matchLabels:
      app: jira
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jira
  name: jira
  namespace: production
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: https
    protocol: TCP
    port: 443
```

**Comment by brancz** [comment] 2018-03-20 13:58
Dupe of #218, although in your case, you can only do blackbox probes on a jira instance, extracting metrics from it would not be whitebox monitoring and you would get all sorts of distorted results. External services would be the wrong approach.

**Closed by brancz** 2018-03-20 13:58 UTC

**Comment by optiomas** [comment] 2018-03-20 17:31
@brancz: Thanks for triaging. We're using this exporter in JIRA: https://github.com/AndreyVMarkelov/jira-prometheus-exporter/

Not sure what you mean by external services being the wrong approach. The JIRA instance is living outside of our Kubernetes cluster.

**Comment by brancz** [comment] 2018-03-21 09:55
The Jira exporter is a per process exporter, you need to run an instance of the exporter for each Jira server (even each HA pair etc), so pointing Prometheus at an external load balancer address, will give you wonky results.

**Comment by optiomas** [comment] 2018-03-21 12:03
We’re running a single instance :-)

**Comment by brancz** [comment] 2018-03-21 13:27
I'll put my infra hat on and say you should, but in terms of metrics in your situation that should be fine then, would faking the Service/Endpoints object work for you?

**Comment by optiomas** [comment] 2018-03-21 17:10
>  would faking the Service/Endpoints object work for you, so you can use a ServiceMonitor "normally"?

How would that be different from the manifests above?

**Comment by brancz** [comment] 2018-03-22 08:38
Ah I apologize, I've read through too many threads recently. I imagine #1086 would solve that problem then :slightly_smiling_face:
