### ISSUE TITLE
node-exporter error: Path /proc is mounted on /proc but it is not a shared or slave mount

### ISSUE THREAD

**Issue by bamb00** [coreos/prometheus-operator#1071] opened 2018-03-12 18:01 UTC
**What did you do?**
Deploy prometheus-operator from  contrib/kube-system/hack/cluster-monitoring/deploy

**What did you expect to see?**
prometheus-operator and node-exporter deployed

**What did you see instead? Under which circumstances?**
* node-exporter failed with, 
       
       failed to open log file "/var/log/pods/3722965f-2616-11e8-8fc0-02420ac00002/node-exporter_7.log": open /var/log/pods/3722965f-2616-11e8-8fc0-02420ac00002/node-exporter_7.log: no such file or directory

**Environment**

* Kubernetes version information:

       Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:40:06Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
       Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:40:06Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

	hyperkube, dind

* Node-exporter Logs:

       Error: failed to start container "node-exporter": Error response from daemon: linux mounts: Path /proc is mounted on /proc but it is not a shared or slave mount

**Comment by brancz** [comment] 2018-03-13 03:03
Given that this is the very first time I am hearing of this, is there anything special about your cluster and or how you run the kubelet?

**Comment by brancz** [comment] 2018-04-12 08:03
Closing due to lack of information. Feel free to comment, re-open or open a new issue if you have more concrete information on how to reproduce your issue, but this doesn’t seem like a problem with the Prometheus Operator.

**Closed by brancz** 2018-04-12 08:03 UTC
