### ISSUE TITLE
prometheus-operator restart complaining about namespaces

### ISSUE THREAD

**Issue by nrobert13** [coreos/prometheus-operator#1944] opened 2018-09-27 09:45 UTC
**What did you do?**
installed kube-prometheus.
**What did you expect to see?**
no error messages during prometheus-operator startup.
**What did you see instead? Under which circumstances?**
when I kill the operator pod and it gets restarted, it is complaining about all the existing namespaces with the following error. After a while the error messages are gone.

````
level=error ts=2018-09-27T09:06:44.594291197Z caller=operator.go:734 component=prometheusoperator msg="get namespace to enqueue Prometheus instances failed: namespace \"monitoring\" does not exist" err=null
````

**Environment**
dev
* Prometheus Operator version:
````
    Image:         quay.io/coreos/prometheus-operator:v0.23.2
    Image ID:      docker-pullable://quay.io/coreos/prometheus-operator@sha256:8211b3eb30cb8591ddf536f1cf62100f5c97659c14d18dd45001acf94dafd713
````
* Kubernetes version information:
````
kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
````

* Kubernetes cluster kind: 

kubespray

* Manifests:

```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    k8s-app: prometheus-operator
  name: prometheus-operator
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: prometheus-operator
  template:
    metadata:
      labels:
        k8s-app: prometheus-operator
    spec:
      containers:
      - args:
        - --kubelet-service=kube-system/kubelet
        - --logtostderr=true
        - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
        - --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.23.2
        image: quay.io/coreos/prometheus-operator:v0.23.2
        name: prometheus-operator
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      nodeSelector:
        beta.kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: prometheus-operator

```

* Prometheus Operator Logs:

for every existing namespace the following message many times ( but not the same count for all nmaepsaces ) ..

```
level=error ts=2018-09-27T09:06:44.594291197Z caller=operator.go:734 component=prometheusoperator msg="get namespace to enqueue Prometheus instances failed: namespace \"monitoring\" does not exist" err=null


```

**Comment by brancz** [comment] 2018-09-27 13:09
Curious. This sounds like the namspace informer is in an inconsistent state with an event that came in. @squat @mxinden maybe we're not waiting for an initial sync correctly?

@nrobert13 does this happen randomly in the logs or just once (or a few times) at startup and then stops?

**Comment by squat** [comment] 2018-09-28 10:08
I'll give this a spin to try and reproduce and report back. If it happens after killing, then it should also happen randomly on first start as these are the same for us since we keep no state.

**Comment by quikstrike** [comment] 2018-10-01 17:37
I am also getting this same error. This is happening on pod startup, and re-creating the pod does not fix the issue, the operator just crashLoops from here.

**Comment by squat** [comment] 2018-10-02 09:52
Correct me if I am wrong, but from @nrobert13's description, it does _not_ seem like the operator is crashlooping but rather logging non-critical errors an eventually stabilizing, which differentiates it from your experience, @quikstrike.

**Comment by squat** [comment] 2018-10-02 10:00
@nrobert13 sorry for the delay. The root of the issue is that release v0.23.2 did not include the recent fixes to synchronize object caches before running the informers [0]. The result is that the operator will log an error if it tries to operate on an object that is not yet in the cache. This is non-fatal; the operator will simply try again later. Eventually, the cache will catch up and the operator will function normally.

This issue is already fixed in master and will be available in the next release. I'll close this issue for now as the issue is already fixed and is simply awaiting a new release.

[0] https://github.com/coreos/prometheus-operator/pull/1813

**Closed by squat** 2018-10-02 10:00 UTC

**Comment by nrobert13** [comment] 2018-10-02 11:16
sorry for the delay, thanks to everyone.

**Comment by quikstrike** [comment] 2018-10-02 21:16
@squat You are correct about my experience. Should I create a new ticket to address my issue? It wasn't clear from your last message if your reply also addressed my issue. I'm happy to open another ticket for the sake of keeping things clean. Let me know.
