### ISSUE TITLE
grafana extravars not quoting strings that needs to be quoted.

### ISSUE THREAD

**Issue by ehvattum** [coreos/prometheus-operator#1106] opened 2018-03-19 11:32 UTC
**What did you do?**
I attempted to set an environment variable in the deployment that is created with the grafana chart.
 `--set extraVars[0].name=GF_AUTH_GOOGLE_ENABLED --set extraVars[0].value="true"` 

**What did you expect to see?**
The envrionment variable `GF_AUTH_GOOGLE_ENABLED` injected into the deployment with the value of `"true"`

**What did you see instead? Under which circumstances?**
The envrionment variable `GF_AUTH_GOOGLE_ENABLED` injected into the deployment with the value of `true` - without the quotes, making the yaml invalid. Different quoting does not help, but generates strings that are escaped in a way that grafana is not picking up.

- `'true'` -> `'''true'''`

I suggest that the values of the extraVars properties in values.yml is quoted in the template.

**Environment**

- Windows 10 64
- Helm Client:2.8.0
- Tiller Version 2.8.1

* Kubernetes version information:

	Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.3-gke.0", GitCommit:"a7b719f7d3463eb5431cf8a3caf5d485827b4210", GitTreeState:"clean", BuildDate:"2018-02-16T18:26:01Z", GoVersion:"go1.9.2b4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

	GCE

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by gianrubio** [comment] 2018-03-20 19:07
This is not a bug in the grafana chart but in helm templating, I can see other users having the same [issue](https://github.com/kubernetes/helm/issues/1707). Seems like a [PR](https://github.com/kubernetes/helm/pull/3599) is open to fix that helm behaviour.

I'm closing this issue because it can be fixed here, feel free to reopen or add more comments.

**Closed by gianrubio** 2018-03-20 19:07 UTC
Labels: helm
