### ISSUE TITLE
Use .spec.podManagementPolicy: "Parallel"

### ISSUE THREAD

**Issue by julianvmodesto** [coreos/prometheus-operator#661] opened 2017-10-03 14:50 UTC
Could we use `.spec.podManagementPolicy: "Parallel"` for prometheuses for Kube 1.8 clusters?

https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#parallel-pod-management

Updates should be rolling, but prometheuses should start in parallel instead of starting sequentially. For example, I run a prometheus with `.spec.replicas: 2`, and the first prometheus takes a long time to startup when crash recovering. Meanwhile, the second prometheus was waiting on the first to startup, but we could have benefited from both prometheus replicas starting up at once.

**Comment by brancz** [comment] 2017-10-04 09:30
Dupe of #491. Happy to add it, just haven't come around doing it yet.

**Closed by brancz** 2017-10-04 09:30 UTC
