### ISSUE TITLE
Using Gi for Memory Requests does not work 

### ISSUE THREAD

**Issue by f0** [coreos/prometheus-operator#370] opened 2017-05-17 09:57 UTC
**What did you do?**
Change the Memory Request from the default to 16Gi for the prometheus pods

**What did you expect to see?**

prometheus pods have a Memory request of 16Gi

**What did you see instead? Under which circumstances?**
No change

**Environment**
CoreOS Stable
prometheus-operator dfc74ae4c704aa4913cf88da89e9f2ceeb8f1d4c
* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2+coreos.0", GitCommit:"79fee581ce4a35b7791fdd92e0fc97e02ef1d5c0", GitTreeState:"clean", BuildDate:"2017-04-19T23:13:34Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

	

* Kubernetes cluster kind: 

	bootkube

* Manifests:

```
paiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: k8s
  labels:
    prometheus: k8s
spec:
  replicas: 2
  version: v1.6.2
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchExpression:
    - {key: k8s-apps, operator: Exists}
  ruleSelector:
    matchLabels:
      role: prometheus-rulefiles
      prometheus: k8s
  resources:
    requests:
      # 2Gi is default, but won't schedule if you don't have a node with >2Gi
      # memory. Modify based on your target and time-series count for
      # production use. This value is mainly meant for demonstration/testing
      # purposes.
      memory: 16Gi
  alerting:
    alertmanagers:
    - namespace: monitoring
      name: alertmanager-main
      port: web
```

* Prometheus Operator Logs:

```
 match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
E0517 09:16:56.418472       1 reflector.go:199] github.com/coreos/prometheus-operator/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1alpha1.Prometheus: quantities mu
st match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
E0517 09:16:57.426980       1 reflector.go:199] github.com/coreos/prometheus-operator/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1alpha1.Prometheus: quantities mu
st match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
E0517 09:16:58.429402       1 reflector.go:199] github.com/coreos/prometheus-operator/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1alpha1.Prometheus: quantities mu
st match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'

```

With Memory request set to G intead of Gi , it does work, however upstream k8s says Gi 
https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/

**Comment by mxinden** [comment] 2017-05-17 15:55
I am having difficulties reproducing this issue on a Kubernetes `1.6.2` (On AWS with the tectonic-installer:1.6.2-tectonic.1) with the *kube-prometheus* manifests. Specifying requested memory via `Gi` does not prevent the pods from starting up. The string "16Gi" does match the RegExp from the error message.

Can you try this again on  a fresh cluster?

**Comment by f0** [comment] 2017-05-17 17:49
@mxinden hm, i can not easy setup a new cluster, because its running on bare Metal..... and its used.
I completly removed the prometheus operator (with hack, teamdown) and added again, same Problem

**Comment by brancz** [comment] 2017-05-18 08:47
@f0 you may want to ensure that StatefulSets are completely deleted after the teardown script. Since the teardown script also deletes the Prometheus Operator it may not clean up the failing StatefulSets, if it was ever able to create.

**Comment by f0** [comment] 2017-05-18 18:53
@brancz  ok, you are right after teardown, there are alertmanager and prometheus StatefulSets and a Prometheus Deployment leftove.
However, if i change the memory request and apply with  kubectl apply -f manifests/prometheus/prometheus-k8s.yaml, it does not work...

If i  change the memory request before installing the operator, it does work.....

**Comment by brancz** [comment] 2017-06-12 10:01
I'll close this here, feel free to reopen if you feel necessary.

**Closed by brancz** 2017-06-12 10:01 UTC
