### ISSUE TITLE
Grafana watcher replacing all dashboards not found on Grafana configmap

### ISSUE THREAD

**Issue by bchanan03** [coreos/prometheus-operator#543] opened 2017-08-06 14:56 UTC
**What did you do?**
Updating Grafana dashboards configmap with Grafana dashboards and applying the configmap 
has deleted all my dashboards created already.

**What did you expect to see?**
Updating Grafana dashboards should not remove dashboards not listed on configmap.
OR enabled/disabled for this change allow user to decide the Grafana watcher policy.

**What did you see instead? Under which circumstances?**
All my previous dashboards were replaced with dashboards found on the Grafana confimap.

**Environment**
Kubernetes 1.5.7
Grafana 4.4.3

* Kubernetes version information:
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.7", GitCommit:"8eb75a5810cba92ccad845ca360cf924f2385881", GitTreeState:"clean", BuildDate:"2017-04-27T10:00:30Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.7", GitCommit:"8eb75a5810cba92ccad845ca360cf924f2385881", GitTreeState:"clean", BuildDate:"2017-04-27T09:42:05Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
Kubernetes running on AWS with CoreOS based OS.

* Manifests:
None

* Prometheus Operator Logs:
None

**Comment by brancz** [comment] 2017-08-07 08:03
This is intended behavior. Because grafana has its built in sqlite database it is extremely hard to run reliably and in a consistent way. The grafana-watcher is intended to make grafana essentially stateless. 

The workflow is intended to be something like this:

1) Grafana is deployed and provisioned with a set of dashboards from the ConfigMap.
2) You create/modify dashboards via the UI.
3) You export the created/modified dashboards via Grafana's export functionality.
4) You check in the files into source control.
5) The ConfigMap is updated from source control.

It's not perfect, for example there is more automation we can build around step 3, and for trying out on staging you could skip step 4.

The point why we built it this way is that it's over-complicated to require to run a replicated database just to have dashboards of which we already have the definitions floating around. This is intended to get some more structure into running Grafana is a consistent, reliable and scalable way.

**Comment by mindw** [comment] 2017-08-15 13:11
Thank you for the very detailed rational @brancz.

The above workflow may produce unfortunate results when employed by two users. Both modify different dashboards and whoever commits first destroys the others uncommitted work. 

Wouldn't simply ignoring unreferenced sources & dashboard be an acceptable compromise?

**Comment by brancz** [comment] 2017-08-15 13:24
Interesting idea @mindw, essentially what you're saying is that we don't wipe _all_ dashboards, but rather only those we have information about in the configmaps... I guess this can be a compromise.

**Comment by whypro** [comment] 2018-04-23 10:02
I've also encountered the same problem as @mindw described.
When some users add new dashboards but not saving (export to file or sync to repo) it yet, all of them will be lost after restarting. I think it may be useful if we don't delete all dashboards before creating. 

What about add a flag or env to support this feature?
`--recreate=true`
If the value is `true`(default), the action is like previous: 
Delete all dashboards/datasources and then recreate them.
When it is `false`, update exists items and create non-exists items.

What do you think? I would help to implement this flag if necessary.

**Comment by brancz** [comment] 2018-04-23 10:13
The grafana watcher is deprecated and will soon be removed (it hasn't been used in the stack for a couple of months now), we recommend switching to Grafana 5.x, which has this functionality built in (including all sorts of strategies for creating/removing).

Closing here.

**Closed by brancz** 2018-04-23 10:13 UTC

**Comment by bamb00** [comment] 2018-08-21 19:27
I was able to find the deprecation notice.  Thanks.

https://github.com/coreos/prometheus-operator/pull/1309
